### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input on method: 'DELETE'

### ISSUE THREAD

**Issue by danb235** [request/request#1024]
I am getting a `Uncaught SyntaxError: Unexpected end of input` error when using `method: 'DELETE'`.  I am using `request@2.40.0`.

Example is in coffeescript.

``` coffeescript
options =
      url: https://api.sample.com + '/users/me?password=' + userpassword
      method: 'DELETE'
      auth:
        bearer: accessToken
      headers:
        'Accept': 'application/json'

request options, (error, response, body) ->
  console.log response.statusCode
```

Results in:

``` bash
Uncaught SyntaxError: Unexpected end of input
at Object.parse (native)
    at Request._callback (/Users/daniel/Projects/test/coffee/src/tasks.coffee:21:19)
    at Request.self.callback (/Users/daniel/Projects/test/node_modules/request/request.js:123:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/daniel/Projects/test/node_modules/request/request.js:1047:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/daniel/Projects/test/node_modules/request/request.js:998:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

The part that really has me confused, if I add `console.log arguments` in the `request` function, I can see the request and response data before the syntax error.  The server is responding with a 204 as I am expecting.  Request just hits this syntax error and everything falls apart. 

If I simply change the method to `GET` I get an expected 405 without issue.

``` coffeescript
options =
      url: https://api.sample.com + '/users/me?password=' + userpassword
      method: 'GET'
      auth:
        bearer: accessToken
      headers:
        'Accept': 'application/json'

request options, (error, response, body) ->
  console.log response.statusCode
```

Results in:

``` bash
405
```

**Comment by stevenspiel** [comment]
thanks for the follow up. that was my issue too!
