### ISSUE TITLE
ESOCKETTIMEDOUT with socks module

### ISSUE THREAD

**Issue by raitucarp** [request/request#1234]
Hi guys, I just want to confirm this..
Is socks module from @mattcg is not updated? because I got this error
Or maybe there is a bug in unrefTimeout?

```
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/apps/myapps/node_modules/request/request.js:828:19)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:92:17)
    at Socket.emitTimeout (http.js:1801:10)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:92:17)
    at Socket._onTimeout (net.js:326:8)
    at Timer.unrefTimeout [as ontimeout] (timers.js:427:13)
```

If this issue is not related, I will post it to socks module repo issue

Thanks

**Comment by kilianc** [comment]
I am getting this all the time when I hit the same load balancer with high concurrency. `ESOCKETTIMEDOUT` is killing me!

**Comment by alexrada** [comment]
did you fix it? I have a similar issue, and I'm looking at options on the load balancer side.
It's an Ningx proxy.
