### ISSUE TITLE
Sending boolean as body for JSON request not working properly

### ISSUE THREAD

**Issue by apoco** [request/request#1281]
When trying to send a JSON boolean value in a request:

```
request({
    method: 'PUT',
    uri: someUrl',
    json: true,
    body: true
})
```

...I get this error:

```
TypeError: First argument needs to be a number, array or string.
    at new Buffer (buffer.js:188:15)
    at Request.init (/home/jacob/Code/request/request.js:596:21)
    at new Request (/home/jacob/Code/request/request.js:282:8)
    at request (/home/jacob/Code/request/index.js:50:10)
    at Test.<anonymous> (/home/jacob/Code/request/tests/test-json-request.js:24:3)
    at Test.bound [as _cb] (/home/jacob/Code/request/node_modules/tape/lib/test.js:59:32)
    at Test.run (/home/jacob/Code/request/node_modules/tape/lib/test.js:72:10)
    at Test.bound [as run] (/home/jacob/Code/request/node_modules/tape/lib/test.js:59:32)
    at Object.next [as _onImmediate] (/home/jacob/Code/request/node_modules/tape/lib/results.js:66:15)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

Is this intentional? Also, is there an easy workaround for this issue?

**Comment by sumeetsolse** [comment]
{
        "fullName": "Ganesh Gonde",
        **"gender": false,**
        "dob": "1985-11-15",
        "mobileNumber": 98959000321,
        "tblMstHobbyDetails": []
}

**Comment by Naveenpatel45** [comment]
why cant i filter with boolean in json .
