### ISSUE TITLE
Error handler should pass the requested uri in the error message when request fails completely

### ISSUE THREAD

**Issue by mikkotikkanen** [request/request#1298]
For those times when fe. there are connection issues on either end and request fails completely then all you get is this...

```
{ [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' }
```

...and stack like this (which at least could be fixed with firing custom error when request gives out error)...

```
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

...which, when you look at the server error-logs, gives you no idea which request and where was the culprit. Would be nice if the requested uri would be added into the error object so that the debugging would get bit easier.

**Comment by CooCooooo** [comment]
:+1:

**Comment by aoberoi** [comment]
:+1:
