### ISSUE TITLE
Error when URI scheme is not specified

### ISSUE THREAD

**Issue by vbauer** [request/request#1318]
POST request to "http://sometime.com" sends fine, but it fails on "sometime.com":

```
/home/vbauer/workspace/js/manet/node_modules/request/request.js:914
  self.req = self.httpModule.request(reqOptions)
                             ^
TypeError: Cannot call method 'request' of undefined
    at Request.start (/home/vbauer/workspace/js/manet/node_modules/request/request.js:914:30)
    at Request.write (/home/vbauer/workspace/js/manet/node_modules/request/request.js:1722:10)
    at write (_stream_readable.js:583:24)
    at flow (_stream_readable.js:592:7)
    at ReadStream.pipeOnReadable (_stream_readable.js:624:5)
    at ReadStream.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at ReadStream.Readable.push (_stream_readable.js:127:10)
```

Maybe it will be better to use "http" as default scheme?

**Comment by saper** [comment]
Is this still an issue? I am getting this:

````
> var r=require('request');
undefined
> var p=r.get('sometime.com');
Error: Invalid URI "sometime.com"
    at Request.init (/home/saper/node_modules/request/request.js:469:31)
    at new Request (/home/saper/node_modules/request/request.js:272:8)
    at request (/home/saper/node_modules/request/index.js:56:10)
    at Function.request.(anonymous function) (/home/saper/node_modules/request/index.js:66:12)
    at repl:1:9
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
> undefined
> var p=r.post('sometime.com');
Error: Invalid URI "sometime.com"
    at Request.init (/home/saper/node_modules/request/request.js:469:31)
    at new Request (/home/saper/node_modules/request/request.js:272:8)
    at request (/home/saper/node_modules/request/index.js:56:10)
    at Function.request.(anonymous function) (/home/saper/node_modules/request/index.js:66:12)
    at repl:1:9
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
> undefined
````

There does not seem to be the way to catch this error with `.on`, however.

**Comment by simov** [comment]
@saper you are correct. The problem is that request uses the same code for initial initialization and initialization after redirect. So in the first case the error event is emitted before it's been registered.

However request can directly throw various other errors during initialization. So it's a good idea to construct your code like this:

```js
try {
  var r = request.post('someurl.com')
} catch (err) {
  // this will catch any error thrown
  // including the emitted ones during the initial initialization
  // they still have the correct error message
}
// if initialization have passed
// you can register for the error event
r.on('error', function (err){}).pipe(...)
```

As for having default URL scheme that's probably not a good idea. If you take a look at the nodejs http and https modules, they always initiate the requests through specific instance. In request the specific instance is set internally based on the protocol specified in the url string.

**Comment by saper** [comment]
@simov Do you think I should file a separate bug? I have found a workaround using a callback:

````
> var r = require('request');
undefined
> var p = r('sometime.com', function (e, r, b) { console.log('CB ', e); console.log(r); }).on('error', function(e) { console.log('Event: ', e) });
CB  [Error: Invalid URI "sometime.com"]
undefined
undefined
````

So the event handler does not get called, but the callback runs. Or is `error` callback specifically designed only for true runtime errors (like `Error: getaddrinfo ENOTFOUND aaaasometime.com`) and not for malformed parameters?

For host not found problem we get:

````
> var p = r.get('http://aaaasometime.com', function (e, r, b) { console.log('CB ', e); console.log(r); }).on('error', function(e) { console.log('Event: ', e) });
undefined
> CB  { [Error: getaddrinfo ENOTFOUND aaaasometime.com]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'aaaasometime.com' }
undefined
Event:  { [Error: getaddrinfo ENOTFOUND aaaasometime.com]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'aaaasometime.com' }

undefined
````

**Comment by simov** [comment]
Like I said, you can't register for error event, before the request object have been initialized. In the first example request emits/throws during initialization. When you have a request callback specified, request binds that callback to the error event internally, but then again your own error event handler is not registered at that point.

And still request can throw directly in some places during initialization, in these cases you won't be able to catch the error even inside the request callback.

**Comment by saper** [comment]
Thanks. I think I understand it now. In the object-oriented speak, you don't want to return any new instance of the object (`new` should fail via the exception), because otherwise you would need to return something implementing `EventEmitter` interface.

**Comment by simov** [comment]
Actually your example is very good. I think most of the people would expect to catch the error either in the request callback or in the on.error event handler. Request inherits Stream once you require the module, so it is an EventEmitter from the start.

One possible workaround for this issue would be to replace all instances of

```js
self.emit('error', new Error('...'))
```

during initialization with

```js
setTimeout(self.emit.bind(self, 'error', new Error('...')), 0)
```

That way your external on.error handler will be registered before the error is emitted, and therefore the error will be received either in the request callback or in your error event handler. In case of missing request callback and error event handler the error will be thrown anyway

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Invalid URI "google.com"
```

Of course using setTimeout is unreliable, but I can't think of any other solution.
