### ISSUE TITLE
Error: DelayedStream#maxDataSize of 2097152 bytes exceeded.

### ISSUE THREAD

**Issue by jeremiahlee** [request/request#1355]
When downloading a large file that does not have a defined `Content-Length` (i.e. it's using `Transfer-Encoding: chunked`), I'm encountering this error:

```
Error: DelayedStream#maxDataSize of 2097152 bytes exceeded.
    at FormData.CombinedStream._checkDataSize (/opt/apps/1421199886807/0-Worker/package/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:165:19)
    at Request.emit (events.js:117:20)
    at Request.source.emit (/opt/apps/1421199886807/0-Worker/package/node_modules/form-data/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js:30:21)
    at IncomingMessage.<anonymous> (/opt/apps/1421199886807/0-Worker/package/node_modules/request/request.js:1263:12)
    at IncomingMessage.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (_stream_readable.js:765:14)
    at IncomingMessage.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
```

`maxDataSize` can be overridden according to the `delayed-stream` package [documentation](https://github.com/felixge/node-delayed-stream#buffer-limits), but this does not seem configurable from `request`.

Here is an example use that will fail, but it's admittedly not particularly insightful:

``` js
request.get({
  url: getUrl,
  headers: {
    Authorization: oauth1Header
  },
  timeout: 18000
}, function(err, httpResponse, body) {
    console.log('download done');
});
```

**Comment by froatsnook** [comment]
I wasn't able to reproduce this.  I was able to send `request` 100MB of chunked data without any problems.  What versions of node and request are you using?  What happens when you run the following?

```
'use strict'

var http = require('http')
  , request = require('request')

var targetSize = 2*1024*1024 + 1
var requests = Math.ceil(targetSize/8096)

var s = http.createServer(function(req, res) {
  res.statusCode = 200
  res.setHeader('X-PATH', req.url)

  var sent = 0
  ;(function sender() {
    if (sent === targetSize) {
      process.stdout.write("\r")
      res.end()
      return
    }

    var len = Math.min(targetSize - sent, 8096)
    var chunk = new Buffer(len)
    for (var i = 0; i < len; i++) {
      chunk[i] = "A"
    }

    res.write(chunk)
    sent += len

    if (sent%(8096*Math.ceil(requests/100)) === 0) {
      process.stdout.write("\r" + Math.ceil(sent/8096/requests*100) + "%")
    }

    setTimeout(sender, 0)
  })()
})

s.listen(6767)

request.get({
  url: 'http://localhost:6767/hugefile',
  timeout: 18000
}, function(err, resp, body) {
  console.log(resp.headers)
  console.assert(body.length === targetSize)
  console.log("Got %sM of 'A'", Math.floor(body.length/1024/1024))
  console.log("OK")

  s.close()
})
```
