### ISSUE TITLE
cannot PUT with boolean body

### ISSUE THREAD

**Issue by JorisBolsens** [request/request#1372]
I am unable to use request with the Nest rest API as some variables have to be in boolean form.

for instance if I do
```javascript
  var opts = "devices/thermostats/"+deviceID+
    "/"+variable+ //variable is fan_timer_active
    "?auth="+token;
  request.put({
    url:"https://developer-api.nest.com/"+opts,
    body: value, // value is true (boolean not string)
    followAllRedirects: true
  }, cb);
```
I get
```
TypeError: First argument needs to be a number, array or string.
    at new Buffer (buffer.js:188:15)
    at Request.self._buildRequest (/vagrant/node_modules/request/request.js:442:23)
    at Request.init (/vagrant/node_modules/request/request.js:638:10)
    at new Request (/vagrant/node_modules/request/request.js:131:8)
    at request (/vagrant/node_modules/request/index.js:47:10)
    at Function.request.put (/vagrant/node_modules/request/index.js:81:27)
...
```

if i use `json` instead of `body` it is interpreted as me setting the json flag to true, so nothing is sent in the content body. If I set `json` to `true` and `body` to `true` i get the same error & if I try to call `toString()` Nest gives me an error saying it is invalid type.

I was able to get it working with node https by doing:
```javascript
function httpFollowRedPut(hostname, path, port, value, cb){
  var opts = { 
    hostname: hostname, 
    headers:{'content-type':'application/json'},
    port: port, 
    path: path, 
    method: 'PUT'
  }
  var req = http.request(opts, function(res){
    if (res.statusCode > 300 && res.statusCode < 400 && res.headers.location) {
      var location = url.parse(res.headers.location);
      httpFollowRedPut(location.hostname, location.path, location.port, value, cb)
    } else {
      if(res.statusCode !== 200)
        cb(new Error(res.statusCode));
      else
        cb()
    }
  });
  req.on('error', function(e) {
    cb(e);
  });
  if(!(value instanceof String))
    value = value.toString(); // not sure why i can toString() here but breaks in request

  req.write(value);
  req.end();
}
```

**Comment by nylen** [comment]
Try upgrading to the latest version, `2.51.0`.  We recently fixed handling of non-object JSON values, the following works as expected for me:

```js
var request = require('request');

require('request-debug')(request);

request.put({
    url  : 'http://nylen.tv/test.php',
    body : true,
    json : true
}, function(err, res, body) {
    console.log(err, res && res.statusCode, body);
});
```
