### ISSUE TITLE
Problem installing on v0.10.5

### ISSUE THREAD

**Issue by SetupAPersonalAccount** [request/request#1452]
Minimal test case:

``` bash
$ mkdir test
$ cd test/
$ npm install request
npm http GET https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/aws-sign2
npm http GET https://registry.npmjs.org/stringstream
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/isstream
npm http GET https://registry.npmjs.org/bl
npm http GET https://registry.npmjs.org/caseless
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/stringstream
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/isstream
npm http 304 https://registry.npmjs.org/bl
npm http 304 https://registry.npmjs.org/caseless
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/mime-db
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/assert-plus
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/ctype/0.5.3
npm http GET https://registry.npmjs.org/punycode
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/asn1/0.1.11
npm http 304 https://registry.npmjs.org/ctype/0.5.3
npm http 304 https://registry.npmjs.org/punycode
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/assert-plus
npm ERR! Error: ENOENT, utime '/home/user/test/node_modules/request/node_modules/hawk/node_modules/hoek/.npmignore'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.62-xenU-25-0e6777a-x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "request"
npm ERR! cwd /home/user/test
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! path /home/user/test/node_modules/request/node_modules/hawk/node_modules/hoek/.npmignore
npm ERR! fstream_path /home/user/test/node_modules/request/node_modules/hawk/node_modules/hoek/.npmignore
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call utimes
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib64/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/home/user/test/node_modules/request/node_modules/bl/node_modules/readable-stream'
npm ERR! error rolling back  request@2.53.0 { [Error: ENOTEMPTY, rmdir '/home/user/test/node_modules/request/node_modules/bl/node_modules/readable-stream']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/home/user/test/node_modules/request/node_modules/bl/node_modules/readable-stream' }
npm ERR! Error: No compatible version found: assert-plus@'^0.1.5'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5"]
npm ERR!     at installTargetsError (/usr/lib64/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /usr/lib64/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/lib64/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.62-xenU-25-0e6777a-x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "request"
npm ERR! cwd /home/user/test
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! Error: ENOENT, lstat '/home/user/test/node_modules/request/node_modules/hawk/node_modules/boom/.npmignore'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.62-xenU-25-0e6777a-x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "request"
npm ERR! cwd /home/user/test
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! path /home/user/test/node_modules/request/node_modules/hawk/node_modules/boom/.npmignore
npm ERR! fstream_path /home/user/test/node_modules/request/node_modules/hawk/node_modules/boom/.npmignore
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib64/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/user/test/node_modules/request/node_modules/hawk/node_modules/cryptiles/.npmignore'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.62-xenU-25-0e6777a-x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "request"
npm ERR! cwd /home/user/test
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! path /home/user/test/node_modules/request/node_modules/hawk/node_modules/cryptiles/.npmignore
npm ERR! fstream_path /home/user/test/node_modules/request/node_modules/hawk/node_modules/cryptiles/.npmignore
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib64/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/user/test/node_modules/request/node_modules/hawk/node_modules/sntp/.npmignore'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.62-xenU-25-0e6777a-x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "request"
npm ERR! cwd /home/user/test
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! path /home/user/test/node_modules/request/node_modules/hawk/node_modules/sntp/.npmignore
npm ERR! fstream_path /home/user/test/node_modules/request/node_modules/hawk/node_modules/sntp/.npmignore
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib64/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/user/test/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.62-xenU-25-0e6777a-x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "request"
npm ERR! cwd /home/user/test
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! path /home/user/test/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js
npm ERR! fstream_path /home/user/test/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib64/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/user/test/node_modules/request/node_modules/mime-types/node_modules/mime-db/db.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.62-xenU-25-0e6777a-x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "request"
npm ERR! cwd /home/user/test
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! path /home/user/test/node_modules/request/node_modules/mime-types/node_modules/mime-db/db.json
npm ERR! fstream_path /home/user/test/node_modules/request/node_modules/mime-types/node_modules/mime-db/db.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib64/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/test/npm-debug.log
npm ERR! not ok code 0
```

**Comment by SetupAPersonalAccount** [comment]
No idea if this is in any way related to issue #1414.

In any case, this works:
$ npm install request@2.45.0

(except for: "npm WARN optional dep failed, continuing http-signature@0.10.1").
