### ISSUE TITLE
timeout error throw more than once

### ISSUE THREAD

**Issue by wddqing** [request/request#1454]
when set the timeout parameter and the timeout happen,like this:
var req = request.get('http://website.com/',{timeout:10000});
req.on('response',function(res){
      do something
});
req.on('error',function(e){
    console.error(e);
});
the error callback function will called more than once

**Comment by froatsnook** [comment]
Is it possible that something else is going on?  Maybe you are making this request in a loop?  In my tests `request` only times out once.  What happens when you run the following?

```
'use strict'

var http = require('http')
  , request = require('request')

var s = http.createServer(function(req, res) {
  res.statusCode = 200

  setTimeout(function() {
    res.end('ok')
  }, 10000)
})

s.listen(6767)

var req = request.get('http://localhost:6767/', {
  timeout: 500
})

req.on('response', function(resp) {
  console.log('OK')
  s.close()
})

req.on('error', function(err) {
  console.log('error', err)
})
```

**Comment by malandrew** [comment]
Basically, when a timeout is called, this line is called first:

https://github.com/request/request/blob/9c5f7a411ba68ea71fb45e0efff0ccbc892d26ba/request.js#L972

then this line is called:

https://github.com/request/request/blob/9c5f7a411ba68ea71fb45e0efff0ccbc892d26ba/request.js#L1241

then this line is called:

https://github.com/joyent/node/blob/4d9c81b7e2522c5d5d9d35058cbb0bce1228d360/lib/_http_client.js#L211

then this line is called:

https://github.com/joyent/node/blob/4d9c81b7e2522c5d5d9d35058cbb0bce1228d360/lib/net.js#L485

Where `this._handle` is an instance of TCP per these two lines:

https://github.com/joyent/node/blob/4d9c81b7e2522c5d5d9d35058cbb0bce1228d360/lib/net.js#L879
https://github.com/joyent/node/blob/4d9c81b7e2522c5d5d9d35058cbb0bce1228d360/lib/net.js#L51

Which leads to this error being thrown and emitted:

```
Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketCloseListener (http.js:1522:23)
    at Socket.EventEmitter.emit (events.js:117:20)
    at TCP.close (net.js:465:12)
```

Before this error is emitted:

https://github.com/request/request/blob/9c5f7a411ba68ea71fb45e0efff0ccbc892d26ba/request.js#L975
