### ISSUE TITLE
Uncaught TypeError when passing a JSON body alongside with non-json content-type header.

### ISSUE THREAD

**Issue by lxe** [request/request#1463]
```javascript
var request = require('request');

request({
  uri: 'http://google.com',
  json: true,
  headers: {
    'content-type': 'application/x-www-form-urlencoded'
  },
  body: {
    blah: 'this is json body. it should be string. But I don\'t thing request() should have uncaught TypeErrors'
  },
  method: 'POST'
}, function(error, response, body) {
  console.log(error, response, body);
});
```

This throws

```
/Users/lxe/devel/request-test/node_modules/request/request.js:237
  return str.replace(/[!'()*]/g, function(c) {
             ^
TypeError: Object  has no method 'replace'
    at rfc3986 (/Users/lxe/devel/request-test/node_modules/request/request.js:237:14)
    at Request.json (/Users/lxe/devel/request-test/node_modules/request/request.js:1432:21)
    at Request.init (/Users/lxe/devel/request-test/node_modules/request/request.js:554:10)
    at new Request (/Users/lxe/devel/request-test/node_modules/request/request.js:264:8)
    at request (/Users/lxe/devel/request-test/node_modules/request/index.js:50:10)
    at Object.<anonymous> (/Users/lxe/devel/request-test/test.js:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Instead it should just throw the usual `Error: Argument error, options.body.`. Or serialize the body.

**Comment by simov** [comment]
json/body combinations are a bit convoluted in the code base, though in the readme is specified exactly what data request expects for each case. Once the code base is modulized enough adding type checks won't be a problem I think. Also see this http://en.wikipedia.org/wiki/Duck_typing :)

**Comment by lxe** [comment]
This should generate an error, and emit it, similar to https://github.com/request/request/blob/ddab5e86d38f5a7078002c22d3b288dcd9a8eae3/request.js#L967-L969
