### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by mbejda** [request/request#1497]
I'm going to have to use a different module. I think there is a memory leak. The memory leak manifests its self when there are a lot of requests being made. 
Here is the stack trace : 
<pre>
 (err):     at processImmediate [as _immediateCallback] (timers.js:345:15)
bCrawler-10 (err): (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
bCrawler-10 (err): Trace
bCrawler-10 (err):     at Request.addListener (events.js:160:15)
bCrawler-10 (err):     at Request.init (/root/apps/app/crawler/node_modules/request/request.js:618:8)
bCrawler-10 (err):     at Request.onRequestResponse (/root/apps/app/crawler/node_modules/request/request.js:1127:10)
bCrawler-10 (err):     at ClientRequest.emit (events.js:95:17)
bCrawler-10 (err):     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1692:21)
bCrawler-10 (err):     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
bCrawler-10 (err):     at Socket.socketOnData [as ondata] (http.js:1587:20)
bCrawler-10 (err):     at TCP.onread (net.js:527:27)
bCrawler-10 (err): (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
bCrawler-10 (err): Trace
bCrawler-10 (err):     at Request.addListener (events.js:160:15)
bCrawler-10 (err):     at Request.start (/root/apps/app/crawler/node_modules/request/request.js:937:8)
bCrawler-10 (err):     at Request.end (/root/apps/app/crawler/node_modules/request/request.js:1635:10)
bCrawler-10 (err):     at end (/root/apps/app/crawler/node_modules/request/request.js:676:14)
bCrawler-10 (err):     at Object._onImmediate (/root/apps/app/crawler/node_modules/request/request.js:690:7)
</pre>

**Comment by mbejda** [comment]
potential fix. 
<pre>
process.setMaxListeners(0);
</pre>
