### ISSUE TITLE
Request passes along undefined headers, causing a crash

### ISSUE THREAD

**Issue by panta82** [request/request#1522]
After update to node 0.12 and the latest request (from "~2.27.0" to "~2.54.0"), my app started crashing with this message:

```
_http_outgoing.js:333
    throw new Error('"name" and "value" are required for setHeader().');
          ^
Error: "name" and "value" are required for setHeader().
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at Request.start (/Users/ivan/dev/c-code/swordfish/main/node/node_modules/request/request.js:946:30)
    at Request.end (/Users/ivan/dev/c-code/swordfish/main/node/node_modules/request/request.js:1514:10)
    at end (/Users/ivan/dev/c-code/swordfish/main/node/node_modules/request/request.js:717:14)
    at Immediate._onImmediate (/Users/ivan/dev/c-code/swordfish/main/node/node_modules/request/request.js:731:7)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

It seems the problem is in `_http_client.js`:

```javascript
if (options.headers) {
      var keys = Object.keys(options.headers);
      for (var i = 0, l = keys.length; i < l; i++) {
        var key = keys[i];
        self.setHeader(key, options.headers[key]);
      }
    }
```

One of my headers here is `undefined` (they are auto-generated in some code paths).

I'm not sure if node.js changed or request, but either way, it might not be a bad idea to check if some of these values are `undefined` and just skip them if yes.

**Comment by kevinkid** [comment]
Turns out the length of any object is undefined. Demn !
