### ISSUE TITLE
Error of POST file

### ISSUE THREAD

**Issue by ten319** [request/request#1552]
Hi!
I want to post a file to a https server.but got an error.this is my code:

```js
        var formData = { 
            media: {
            value:  fs.createReadStream(__dirname+'\\test.jpg'),
            options: {
              filename: 'test.jpg',
              contentType: 'image/jpg'
            }
          }
        }
        
        
        var r=request({
            method: 'POST',
            url:url,
            formData:formData
        },function(err,res,body){
            if (!err && res.statusCode == 200) {
                console.log(body);
                fn();
            }else{
                console.log(body);
                fn();
            }
        });
```
and got an Error:

```
_http_outgoing.js:303
    value = value.replace(/[\r\n]+[ \t]*/g, '');
                  ^
TypeError: undefined is not a function
    at storeHeader (_http_outgoing.js:303:19)
    at ClientRequest.OutgoingMessage._storeHeader (_http_outgoing.js:229:9)
    at ClientRequest._implicitHeader (_http_client.js:187:8)
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:423:10)
    at Request.write (C:\Project\ExpressTrack\node_modules\request\request.js:15
23:25)
    at FormData.ondata (stream.js:51:26)
    at FormData.emit (events.js:107:17)
    at FormData.CombinedStream.write (C:\Project\ExpressTrack\node_modules\form-
data\node_modules\combined-stream\lib\combined_stream.js:118:8)
    at FormData.CombinedStream._pipeNext (C:\Project\ExpressTrack\node_modules\f
orm-data\node_modules\combined-stream\lib\combined_stream.js:106:8)
    at FormData.CombinedStream._getNext (C:\Project\ExpressTrack\node_modules\fo
rm-data\node_modules\combined-stream\lib\combined_stream.js:79:10)
```
AND i use:

```js
		var r=request({
			method: 'POST',
			url:url
		},function(err,res,body){
			if (!err && res.statusCode == 200) {
		   		console.log(body);
		   		fn();
		 	}else{
		    	console.log(body);
		 		fn();
		 	}
		});


		var form=r.form();
		form.append('media',fs.createReadStream(__dirname+'/test.jpg'));
```
BUT got the same ERROR

**Comment by simov** [comment]
Your code looks correct. Can you test out separately if `__dirname+'/test.jpg'` are giving you the correct path? Also the path from the first example is a bit different `__dirname+'\\test.jpg'`

**Comment by ten319** [comment]
I check the path is correct, and i use __dirname+'/test.jpg' and __dirname+'\\test.jpg' for the two example,but it return the same error.

**Comment by simov** [comment]
As I said your code looks correct, we have that case covered in our tests, make sure you are using the latest request.

**Comment by kruchone** [comment]
Hey ten319:
Could you print out the value of `form._streams` before and after the append?

**Comment by simov** [comment]
Closing @ten319 let us know if you have any problems with this.
