### ISSUE TITLE
No abort() method on invalid protocol

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [request/request#1588]
If you are redirected to a site with an invalid protocol, request will handle this fine and emits an ```error``` event with the message:

```
[Error: Invalid protocol: mailto:]
```

Now if you want to handle that error and abort the request like this:

```js
var request = require('request');

var requestStream = request('http://httpbin.org/redirect-to?url=mailto:test@example.com');

requestStream
	.on('error', function () {
		console.log('[error]', arguments);
		requestStream.abort();
	});
```

you will get the following exception:

```
/node_modules/request/request.js:1264
    self.response.abort()
                  ^
TypeError: Object #<IncomingMessage> has no method 'abort'
    at Request.abort (/node_modules/request/request.js:1264:19)
    at Request.<anonymous> (/protocol-issue.js:12:17)
    at Request.emit (events.js:95:17)
    at Request.init (/node_modules/request/request.js:591:17)
    at Request.onRequestResponse (/node_modules/request/request.js:1127:10)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socketOnData [as ondata] (http.js:1583:20)
    at TCP.onread (net.js:527:27)
```

due to the ```IncomingMessage``` object not having a ```abort()``` method.

I'm calling the ```abort()``` method here just to make sure that everything is cleaned-up after the request errored-out (no memory leaks).

**Comment by pierreliefauche** [comment]
I ran into this exception too, not even calling `abort()` on Request.

Why would `abort()` be called on an `IncomingMessage` btw? 
Was it meant to be [`destroy()`](https://github.com/nodejs/node/blob/master/lib/_http_incoming.js#L92)?

**Comment by simov** [comment]
> Why would abort() be called on an IncomingMessage btw? 
> Was it meant to be destroy()?

Yep, I think so, it should be fixed here https://github.com/request/request/pull/1958
