### ISSUE TITLE
Error: CookieJar store is not synchronous; use async API instead.

### ISSUE THREAD

**Issue by tlianza** [request/request#1674]
The README shows this example:

```javascript
var j = request.jar()
var request = request.defaults({jar:j})
request('http://www.google.com', function () {
  request('http://images.google.com')
})
```

However, when I run that, as soon as my request executes, I get an error thrown from tough-cookie:
```
Error: CookieJar store is not synchronous; use async API instead.
    at CookieJar.getCookieStringSync (.../test/node_modules/request/node_modules/tough-cookie/lib/cookie.js:1048:13)
    at RequestJar.getCookieString (.../test/node_modules/request/lib/cookies.js:30:20)
    at Request.jar (.../test/node_modules/request/request.js:1467:33)
    at Request.init (.../test/node_modules/request/request.js:473:8)
    at new Request (.../test/node_modules/request/request.js:265:8)
    at request (.../test/node_modules/request/index.js:56:10)
    at .../test/node_modules/request/index.js:64:12
    at Function.<anonymous> (.../test/node_modules/request/index.js:106:12)
```

Is this a feature that requires some different configuration to work? I'm using tough-cookie 2.0.0, per npm.

**Comment by simov** [comment]
Works for me, can you provide a little bit more info about your setup?

**Comment by simov** [comment]
Closing due to inactivity.

**Comment by tlianza** [comment]
Sorry, you're right I oversimplified the example. What I am really trying to do is have a few requests, with different cookie jars.  So, here's where I'm trying to have one that doesn't use cookies (unauthReq) and one that has it's own cookie jar (adminReq):

```javascript
var request  = require('request');
var unauthReq = request.defaults({jar: false});

var adminCookieJar = request.jar('admin');
var adminReq = request.defaults({jar: adminCookieJar});
```

Requests with `adminReq` throw the error above. I'm assuming's because I'm calling `request.defaults` and `request.jar` to create the cookie jar... but, I need to create the cookie jar before I create the request... so I'm not sure what the alternative would be. Thanks!

**Comment by simov** [comment]
I don't think that the `.jar()` method accepts string. Try this:

```js
var request  = require('request');
// cookies are off by default, but if you want to be more explicit that's fine too
var unauthReq = request.defaults();

// the argument is used for setting up a custom cookie store
var adminCookieJar = request.jar();
var adminReq = request.defaults({jar: adminCookieJar});
```

**Comment by tlianza** [comment]
Works! Thanks. Sorry, I'm not sure where I got the impression that request.jar could take a string param. I must have misread an example somewhere.
