### ISSUE TITLE
Timeout option not working

### ISSUE THREAD

**Issue by RavenHursT** [request/request#1676]
I set up the following:

```javascript
var start = Date.now();

var request = require('request');
request({
    url: 'http://localhost:8080/test-connection-length',
    method: 'get',
    timeout: 600000, //10 min
}, function (error, response, body) {
    clearInterval(interval);
    if (error) {
        console.error(error);
        console.error(error.stack);
    }
    console.log('got response: ', response);
});

var interval = setInterval(function(){
    console.log('Waiting: ', (Date.now() - start) / 1000);
}, 1000);
```

The test server endpoint just sits and doesn't respond, writing a similar console log every second as well.

Even though I have a 10min timeout set, the result is the following in the client:

```
Waiting:  116.572
Waiting:  117.577
Waiting:  118.579
Waiting:  119.584
got response:  undefined
{ [Error: socket hang up] code: 'ECONNRESET' }
Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at Socket.socketOnEnd (_http_client.js:300:23)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Process finished with exit code 0
```
Shouldn't this happen at 10mins, not 2?

**Comment by RavenHursT** [comment]
Nevermind.  I wasn't setting the response timeout on the express server. Closing.
