### ISSUE TITLE
TypeError: Cannot read property 'href' of undefined

### ISSUE THREAD

**Issue by phongdaohp** [request/request#1681]
I try use request module to upload file to google drive but when I use, I got error message.

```
node_modules\request\request.js:776
    self.href = self.uri.href ;
                        ^
TypeError: Cannot read property 'href' of undefined
    at Request.start (g:\video_tool\node_modules\request\request.js:776:25)
    at Request.write (g:\video_tool\node_modules\request\request.js:1351:10)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at ReadStream.pipeOnReadable (_stream_readable.js:643:5)
    at ReadStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at ReadStream.Readable.push (_stream_readable.js:128:10)
```

This is my function

```js
var self = this;
   self.request = require('request');
    return self.q.Promise(function (resolve, reject, notify) {
        var options = {
            url: 'https://www.googleapis.com/upload/drive/v2/files?uploadType=resumable',
            headers: {
                Host: 'www.googleapis.com',
                'X-Upload-Content-Type': 'video/*',
                'X-Upload-Content-Length': fs.statSync(self.filepath).size,
                'Authorization': 'Bearer ' + self.tokens.access_token,
                'Content-Length': JSON.stringify(params.metadata).length,
                'Content-Type': 'application/json; charset=utf-8',
                'Accept-Encoding': 'gzip, deflate',
                'Accept-Language': 'en-US,en;q=0.5'
            },
            body: JSON.stringify(params.metadata)
        };
        if (self.proxy) {
            options['proxy'] = self.proxy;
        }
       // Send request and start upload if success
        self.request.post(options, function (error, response, body) {
            if (error) {
                reject(error);
                return;
            }
            if (!response.headers.location && body) {
              //Eroor
            }
            self.location = response.headers.location;
          
    })
```

**Comment by simov** [comment]
Works for me, also your configuration looks correct. Use `request-debug` to see how exactly the request is constructed, also check your `proxy` option.

**Comment by simov** [comment]
@phongdaohp I'm closing this issue, let me know if you have any issues.
