### ISSUE TITLE
Strange behavior "formData"

### ISSUE THREAD

**Issue by Daeren** [request/request#1761]
Code:
```js
var data = {
    "id": 1337,
    "text": "hek",
    "web": true
};

require("request")({
    method: 'POST',
    json: true,
    formData: data,
    uri: "http://www.google.com"
});
```

Error:
```
_http_outgoing.js:433
    throw new TypeError('first argument must be a string or Buffer');
          ^
TypeError: first argument must be a string or Buffer
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:433:11)
    at Request.write (\node_modules\request\request.js:1378:25)
    at FormData.ondata (stream.js:51:26)
    at FormData.emit (events.js:107:17)
    at FormData.CombinedStream.write (\node_modules\request\node_modules\combi
ned-stream\lib\combined_stream.js:118:8)
    at FormData.CombinedStream._pipeNext (\node_modules\request\node_modules\c
ombined-stream\lib\combined_stream.js:106:8)
    at FormData.CombinedStream._getNext (\node_modules\request\node_modules\co
mbined-stream\lib\combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (\node_modules\request\node_modules\c
ombined-stream\lib\combined_stream.js:107:8)
    at FormData.CombinedStream._getNext (J:\node_modules\request\node_modules\co
mbined-stream\lib\combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (\node_modules\request\node_modules\c
ombined-stream\lib\combined_stream.js:107:8)
```

If I change `"web": true` on `"web": 1` - it works perfectly.

**Comment by simov** [comment]
Yep, sending boolean doesn't work, I think the form-data team added more appropriate error message in newer releases.

**Comment by Enelar** [comment]
@simov please make sure that it would rollout.

**Comment by jbecwar** [comment]
This bug got me too.  It wouldn't be so bad if there wasn't so cryptic.

**Comment by EricRabil** [comment]
I've wasted hours trying to diagnose this error before stumbling upon this issue. Please, **please** make the error message more descriptive.

**Comment by mikeal** [comment]
> Yep, sending boolean doesn't work, I think the form-data team added more appropriate error message in newer releases.

any idea which release it was?

we should do one big PR for dep updates and push a new release.

**Comment by simov** [comment]
Not sure what was I referring to. We have the latest form-data in our package.json so apparently a better error message was never added.
