### ISSUE TITLE
ETIMEDOUT occured periodically.

### ISSUE THREAD

**Issue by uzysjung** [request/request#1778]
Hi, I found some issue which request lib didn't disconnect well 
It causes ETIMEDOUT periodically 
-- request version ^2.62.0 node version 0.12.7

```
Error: ETIMEDOUT
    at null.<anonymous> (/var/app/current/node_modules/request/request.js:818:15)
    at wrappedCallback (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:347:23)
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at wrappedCallback (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:438:66)
    at wrapped [as _onTimeout] (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at Timer.listOnTimeout (timers.js:119:15)
150916/172259.405, [request,error:], data: ETIMEDOUT
```

It works fine only during 30min ~ 60min. 
but certain amount of time is reached, all request are ETIMEDOUT during 0.1~0.2sec
and then It works fine only during 30~60min. and over and over

after I replace request library to node.js http.request  it works fine. there's no ETIMEDOUT.

when I used forever options:true , certain amount of time is longer than I didn't.

---

I have relay servers.

client --- relay server(using request library) --- A server

this is relay server code below. 

``` javascript
function (request,reply) {

    var options = {
        url: "A server URL",
        qs: request.query, 
        timeout: config.request.timeout,
    };
    request(options, function (error, response, body) {
        if (error) {
            reply(error);
            return;
        } else if (200 != response.statusCode) {
            reply(new Error('can not get user-reco - statusCode' +response.statusCode));
            return;
        }
        var result = JSON.parse(body);
        reply(result);
    });
}
```

**Comment by calibr** [comment]
what value of timeout do you use? and if you can provide complete isolated example it would be very useful.

**Comment by uzysjung** [comment]
I used 3s  , 5s , 10s , default value
this issue occurred all environments.

**Comment by kxjhcs** [comment]
when i send a large amount of requests, I have the same problem...

`at Timeout._onTimeout (C:\Users\Administrator\Desktop\yunnan\node_modules\request\request.js:772:15)
at tryOnTimeout (timers.js:224:11)
at Timer.listOnTimeout (timers.js:198:5) code: 'ETIMEDOUT', connect: false }`

**Comment by kxjhcs** [comment]
when i send l amount of requests,  I have the same problem.

print this always,
`{ Error: ETIMEDOUT
at Timeout._onTimeout (C:\Users\Administrator\Desktop\yunnan\node_modules\request\request.js:772:15)
at tryOnTimeout (timers.js:224:11)
at Timer.listOnTimeout (timers.js:198:5) code: 'ETIMEDOUT', connect: false }
13535
{ Error: ETIMEDOUT
at Timeout._onTimeout (C:\Users\Administrator\Desktop\yunnan\node_modules\request\request.js:772:15)
at tryOnTimeout (timers.js:224:11)`

**Comment by mdumrauf** [comment]
Same problem here

**Comment by kilianc** [comment]
+1

**Comment by FredKSchott** [comment]
Can anyone share code that we can use to reproduce / track this down? It's impossible to say what's happening here with the stack trace alone
