### ISSUE TITLE
pipe response of request to multipart request error

### ISSUE THREAD

**Issue by kevinprotoss** [request/request#1780]
Hi,

I tried to pipe the response of a request into another multipart request. However it doesn't work. I always get such an error `[Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write'`

What does this mean?

The code is like the following:

```js
let res = request.get('http://localhost:8090/banner.jpg');
let req = request
  .put('http://localhost:8080/test.jpg', {
    formData: {
      file: res
    }
  })
  .on('response', (response) => {
    console.log('statusCode', response.statusCode);
  })
  .on('error', (err) => {
    console.log(err);
  });
```

Anything else I did wrong?
I tried to use `form-data` module directly and it works for me. Therefore I create an issue here. I guess it might be the reason of `request` module. 
In addition, the same code above works if I put a file stream in the formData. That's really wierd...

Bg,
Kevin

**Comment by simov** [comment]
Put `encoding:null` in your `banner.jpg` request.

**Comment by cui-liqiang** [comment]
I also got the same issue in the following code. And I've added the encoding:null flag.
```
var request = require('request');
var fs = require('fs');

var upload = request.post({url:"http://localhost:3000/file-upload",
    formData: {my_file: {value: request({url:'http://localhost:3001/', encoding:null}), options: {
        filename: 'sample.zip'
    }}}
});
```

The output is :
```
Error: write EPIPE
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at WriteWrap.afterWrite (net.js:764:14)
{ [Error: write EPIPE]
  code: 'EPIPE',
  errno: 'EPIPE',
  syscall: 'write',
  address: undefined }
```
Two services on 3000 and 3001 are like the following:
```
var express = require('express');
var app = express();
var fs = require('fs');

app.get('/',function(req, res) {
    var file = fs.readFileSync(__dirname + '/file_for_download.zip', 'binary');
    res.write(file, 'binary');
    res.end();
});

app.listen(3001);
```
```
var express = require('express');
var multer = require('multer');

var app = express();
app.use(multer({
    dest: "./updloads"
}));

app.post('/file-upload', function(req, res, next) {
    console.log(req.body);
    console.log(req.files);
    res.end();
});

app.listen(3000);
```
