### ISSUE TITLE
Handle null value in form parameters

### ISSUE THREAD

**Issue by germanattanasio** [request/request#1832]
The code below fails because `key` has `null` as value:
```javascript
request({
  url: 'http://service.com/upload',
  method: 'POST',
  formData: {
    foo: 'bar',
    key: null
  }
});
```

Stacktrace:
```
if (value.hasOwnProperty('value') && value.hasOwnProperty('options')) {
               ^
TypeError: Cannot read property 'hasOwnProperty' of null
    at appendFormValue (/Users/germana/workspace/node-sdk/node_modules/request/request.js:330:16)
    at Request.init (/Users/germana/workspace/node-sdk/node_modules/request/request.js:344:11)
    at new Request (/Users/germana/workspace/node-sdk/node_modules/request/request.js:140:8)
    at request (/Users/germana/workspace/node-sdk/node_modules/request/index.js:55:10)
    at Object.<anonymous> (/Users/germana/workspace/node-sdk/dialog.js:4:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

I was thinking on create a PR but I don't know how do you want to deal with this scenario?

1. Ignore the field
1. Leave the error as it is and invalidate this issue
1. Send "null"
1. ...

**Comment by simov** [comment]
The field should be ignored. The underlying [form-data](https://github.com/form-data/form-data) module will most likely throw an error anyway. Stringifying nulls and booleans is language specific and different servers may expect different formats.

**Comment by germanattanasio** [comment]
thanks @simov

**Comment by krusk** [comment]
I have the same issue.

**Comment by wilk** [comment]
+1

**Comment by markusila** [comment]
+1

**Comment by simov** [comment]
Request only passes the values to the underlying form-data module. The form-data team is planning to stringify null values in v2.0, see https://github.com/form-data/form-data/issues/147

I just added a test here https://github.com/request/request/pull/2208 that expects the underlying form-data module to throw when the value is null. So it still throws, but not in request.
