### ISSUE TITLE
Unable to upload file on nodejs 4.2.1 with request 2.65.0

### ISSUE THREAD

**Issue by vodolaz095** [request/request#1846]
For this code in unit tests:

```javascript

      request({
        'method': 'POST',
        'headers': {
          'huntKey': 'test123'
        },
        'formData': {
          'file': fs.createReadStream(__dirname + '/2_27.jpg'),
          'doIndex': false
        },
        'url': 'http://localhost:' + port + '/api/v1/package/' + packageId + '/attachment'
      }, function (error, response, body) {
         //do things
      });

```

I have this stacktrace

```

TypeError: first argument must be a string or Buffer
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:445:11)
    at Request.write (/home/projects/vodolaz095/endcloud/endowcloud/node_modules/request/request.js:1362:25)
    at FormData.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)
    at FormData.emit (events.js:169:7)
    at FormData.CombinedStream.write (/home/projects/vodolaz095/endcloud/endowcloud/node_modules/request/node_modules/combined-stream/lib/combined_stream.js:118:8)
    at FormData.CombinedStream._pipeNext (/home/projects/vodolaz095/endcloud/endowcloud/node_modules/request/node_modules/combined-stream/lib/combined_stream.js:106:8)
    at FormData.CombinedStream._getNext (/home/projects/vodolaz095/endcloud/endowcloud/node_modules/request/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (/home/projects/vodolaz095/endcloud/endowcloud/node_modules/request/node_modules/combined-stream/lib/combined_stream.js:107:8)
    at FormData.CombinedStream._getNext (/home/projects/vodolaz095/endcloud/endowcloud/node_modules/request/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (/home/projects/vodolaz095/endcloud/endowcloud/node_modules/request/node_modules/combined-stream/lib/combined_stream.js:107:8)
    at FormData.<anonymous> (/home/projects/vodolaz095/endcloud/endowcloud/node_modules/request/node_modules/combined-stream/lib/combined_stream.js:91:10)
    at FormData.<anonymous> (/home/projects/vodolaz095/endcloud/endowcloud/node_modules/request/node_modules/form-data/lib/form_data.js:201:5)
    at FormData.CombinedStream._getNext (/home/projects/vodolaz095/endcloud/endowcloud/node_modules/request/node_modules/combined-stream/lib/combined_stream.js:84:3)
    at emitNone (events.js:72:20)
    at DelayedStream.emit (events.js:166:7)
    at DelayedStream._handleEmit (/home/projects/vodolaz095/endcloud/endowcloud/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js:82:15)
    at ReadStream.source.emit (/home/projects/vodolaz095/endcloud/endowcloud/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js:29:19)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickDomainCallback (node.js:394:17)
```

File exists, it is readable, endpoint works in browser.

**Comment by simov** [comment]
Can you try with `'doIndex': 'false'` - set the boolean value of the multipart item to string.

**Comment by vodolaz095** [comment]
@simov thanks, it works. Let the God grant you good health and happiness!
