### ISSUE TITLE
Cannot find module 'readable-stream/duplex'

### ISSUE THREAD

**Issue by fortyMiles** [request/request#1877]
# Problem

I run my js script in Mac OX, I have installed *request* module.
But when I run the script, it shows the *Cannot find module 'readable-stream/duplex'* error.

#  Run Environment

Mac OX, node v0.10.32,  npm 3.3.10.

# Error Stack

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'readable-stream/duplex'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kouminquan/Workspaces/Xinshu/my-family/pusher/pusher/node_modules/request/node_modules/bl/bl.js:1:82)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
 thanks ~

**Comment by fortyMiles** [comment]
Okay.. After I run 
```
$ sudo npm install -g npm
```
and install *request*, it works ~
