### ISSUE TITLE
HPE_INVALID_HEADER_TOKEN error while fetching an image

### ISSUE THREAD

**Issue by ApsOps** [request/request#1884]
Steps to reproduce:

``` javascript
var request = require('request')
request('https://facestore.pt/images/11522/products/10_1_20151002092830_img_b.jpg')
```

I receive the following error:

``` javascript
{ [Error: Parse Error] bytesParsed: 152, code: 'HPE_INVALID_HEADER_TOKEN' }
```

Stack trace:

``` javascript
Error: Parse Error
   at Error (native)
   at TLSSocket.socketOnData (_http_client.js:305:20)
   at emitOne (events.js:77:13)
   at TLSSocket.emit (events.js:169:7)
   at readableAddChunk (_stream_readable.js:146:16)
   at TLSSocket.Readable.push (_stream_readable.js:110:10)
   at TLSWrap.onread (net.js:523:20)
```

**Comment by evanlucas** [comment]
`curl -IS 'https://facestore.pt/images/11522/products/10_1_20151002092830_img_b.jpg'`

returns 

```
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 09 Nov 2015 02:58:16 GMT
Content-Type: image/jpeg
Content-Length: 69633
Connection: close
X-Frame-Options="ALLOW-FORM: facebook.com"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE, PUT
Access-Control-Max-Age: 1000
Access-Control-Allow-Headers: x-requested-with, Content-Type, origin, authorization, accept, client-security-token
Last-Modified: Fri, 02 Oct 2015 08:28:30 GMT
ETag: "aa08cc-11001-5211af2ce60c3"
Accept-Ranges: bytes
Strict-Transport-Security: max-age=31536000; includeSubdomains
```

I'm guessing that the `X-Frame-Options="ALLOW-FORM: facebook.com"` is what is causing it in node's http parser.

**Comment by simov** [comment]
@evanlucas, good point! Should we address this issue in the node's tracker?

**Comment by evanlucas** [comment]
I would probably open an issue at https://github.com/nodejs/http-parser/issues.

**Comment by regevbr** [comment]
https://github.com/creationix/http-parser-js fixed the issue for me
