### ISSUE TITLE
CookieJar 

### ISSUE THREAD

**Issue by gdidier** [request/request#1939]
Hi,
It's seems there's a problem with request( version 2.67) with tough-cookie 2.2.1

```
TypeError: Cannot read property 'secure' of undefined
    at CookieJar.getCookies (/home/guillaume/Bureau/optionizor/node_modules/tough-cookie/lib/cookie.js:1031:23)
    at CookieJar.getCookieString (/home/guillaume/Bureau/optionizor/node_modules/tough-cookie/lib/cookie.js:1132:19)
    at Request.jar (/home/guillaume/Bureau/optionizor/node_modules/request/request.js:1302:33)
    at Request.init (/home/guillaume/Bureau/optionizor/node_modules/request/request.js:313:8)
```

cf :

``` js
var t = require("tough-cookie");
var jar = new t.CookieJar();

request.post({
        url:searchaction,
        body:bodystr,
        headers:{
                "Content-Type": "application/x-www-form-urlencoded",
                "User-agent":agent,
                "Referer":referer
        },
        jar: jar
    }, function(error, response, body){
```

**Comment by simov** [comment]
Did you tried with `var jar = request.jar()`? Request depends on `tough-cookie` internally.

**Comment by colthreepv** [comment]
I have the same problem, does not seem possible to use `tough-cookie` to benefit of the full extent of its API.

**Comment by areinmeyer** [comment]
I had this issue as well.  Seems that creating a CookieJar from tough-cookie and trying to use that with request causes this issue.  What I was able to do was create the jar as @simov suggested, but then added a line after that with ````jar._jar.rejectPublicSuffixes = false;````  

Since that was the whole reason for me needing to directly use tough-cookie, it allowed me to get around this error.  Not sure what your need for using tough-cookie directly was, but hope that helps.  

I think there's some assumptions that tough-cookie makes that request doesn't, especially in using the getCookieString function.

**Comment by Christilut** [comment]
Same problem here (request-promise):
```js
this.jar = new tough.CookieJar()

rp = rp.defaults({
      jar: this.jar
})
```

then on a request:
```
     TypeError: Cannot read property 'secure' of undefined
      at CookieJar.getCookies (node_modules/tough-cookie/lib/cookie.js:1032:23)
      at CookieJar.getCookieString (node_modules/tough-cookie/lib/cookie.js:1133:19)
      at Request.jar (node_modules/request/request.js:1361:33)
      at Request.init (node_modules/request/request.js:315:8)
      at Request.RP$initInterceptor [as init] (node_modules/request-promise/lib/rp.js:137:25)
      at new Request (node_modules/request/request.js:142:8)
      at request (node_modules/request/index.js:55:10)
      at node_modules/request/index.js:102:12
      at Gazelle._login (index.js:41:12)
      at Context.it (test/test.js:57:7)
```

**Comment by JamesTheHacker** [comment]
Same problem. What's the fix?

**Comment by herlon214** [comment]
@areinmeyer I am using PhantomJS and exporting their cookies with [Phantom2JAR](https://www.npmjs.com/package/phantom2jar). I need to use these cookies in this lib, have you any idea?

**Comment by cspotcode** [comment]
Request uses a wrapper around tough-cookie's jar implementation.  Here's my workaround to get full access to tough-cookie's API.

```
const jar = request.jar();
const toughCookieJar = jar._jar;

// or if I must create the jar myself, perhaps to pass additional options...
// Note that request enables looseMode on the internal jar.  You probably need to do this as well; I haven't tested.
const toughCookieJar = new toughCookie.CookieJar(undefined, {looseMode: true});
const jar = request.jar();
jar._jar = toughCookieJar;
```

**Comment by cloewen8** [comment]
This pull request should not be closed. It is simply awaiting further review or merging.
