### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by yejijie** [request/request#1985]
Here is the code:
```js
var options = {
    url:url,
    method: 'post',
    form: {
        sense: sense,
        data:packet
    }
};

request(options, function (err, resp, body) {
    if(err){
        console.log('err:'+err);
    }
});
```
The error:
```
/Users/Jaye/WebstormProjects/taghome2/trunk/cloud/node_modules/request/node_modules/qs/lib/stringify.js:30
internals.stringify = function (obj, prefix, generateArrayPrefix, strictNullHa
                               ^
RangeError: Maximum call stack size exceeded
    at Object.internals.stringify (/Users/Jaye/WebstormProjects/taghome2/trunk/cloud/node_modules/request/node_modules/qs/lib/stringify.js:30:32)
    at Object.internals.stringify (/Users/Jaye/WebstormProjects/taghome2/trunk/cloud/node_modules/request/node_modules/qs/lib/stringify.js:86:46)
    at Object.internals.stringify (/Users/Jaye/WebstormProjects/taghome2/trunk/cloud/node_modules/request/node_modules/qs/lib/stringify.js:83:46)
    at Object.internals.stringify (/Users/Jaye/WebstormProjects/taghome2/trunk/cloud/node_modules/request/node_modules/qs/lib/stringify.js:86:46)
    at Object.internals.stringify (/Users/Jaye/WebstormProjects/taghome2/trunk/cloud/node_modules/request/node_modules/qs/lib/stringify.js:86:46)
    at Object.internals.stringify (/Users/Jaye/WebstormProjects/taghome2/trunk/cloud/node_modules/request/node_modules/qs/lib/stringify.js:83:46)
    at Object.internals.stringify (/Users/Jaye/WebstormProjects/taghome2/trunk/cloud/node_modules/request/node_modules/qs/lib/stringify.js:86:46)
    at Object.internals.stringify (/Users/Jaye/WebstormProjects/taghome2/trunk/cloud/node_modules/request/node_modules/qs/lib/stringify.js:86:46)
    at Object.internals.stringify (/Users/Jaye/WebstormProjects/taghome2/trunk/cloud/node_modules/request/node_modules/qs/lib/stringify.js:83:46)
    at Object.internals.stringify (/Users/Jaye/WebstormProjects/taghome2/trunk/cloud/node_modules/request/node_modules/qs/lib/stringify.js:86:46)
```
Please, if you have any idea.
Thanks in advance.

**Comment by BradRuderman** [comment]
I am also having this issue. I believe its related to some nested stringified json.

**Comment by simov** [comment]
Yep, check the data structure that you are passing to `form`.
