### ISSUE TITLE
converting this cURL call with request

### ISSUE THREAD

**Issue by namlook** [request/request#2023]
Hi,

I went into a silly issue and I'm seeking help with this one. I try to translate this curl command:

```
curl --digest --user dba:dba --url "http://192.168.99.100:32772/sparql-graph-crud-auth?graph-uri=http://graph.org" -X POST -T file.txt
```

This will stream a file into a server via a POST request using a digest authentification. I try the following:

``` javascript
const request = require('request');
const graphUri = encodeURIComponent('http://graph.org');
const url = `http://192.168.99.100:32772/sparql-graph-crud-auth?graph-uri=${graphUri}`;

let server = request.post(url).auth('dba', 'dba', false);
let infile = fs.createReadStream('./file.txt');


server.on('error', (error) => {
    console.error(error);
});

infile.pipe(server);
```

but the `console.error` display this error:

```
{ [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
```

What is wrong ? Any ideas ?

Thanks a lot.

**Comment by SimonSchick** [comment]
Can you log error.stack instead?

**Comment by namlook** [comment]
Not much, `error.stack` is giving me:

```
Error: write EPIPE
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at WriteWrap.afterWrite (net.js:763:14)
```

here he the full display with node 5.5:

```
{ [Error: write EPIPE]
  code: 'EPIPE',
  errno: 'EPIPE',
  syscall: 'write',
  address: undefined }
Error: write EPIPE
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at WriteWrap.afterWrite (net.js:763:14)
{ [Error: write EPIPE]
  code: 'EPIPE',
  errno: 'EPIPE',
  syscall: 'write',
  address: undefined }
Error: write EPIPE
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at WriteWrap.afterWrite (net.js:763:14)
```

I just added `console.log(error.stack)` under the line `console.log(error)`;
