### ISSUE TITLE
Error: Parse Error after multiple requests.

### ISSUE THREAD

**Issue by Amberlamps** [request/request#2034]
Request version: 2.67.0
Node version: 5.5.0 or 4.2.2

I have an array of urls to ebay items. If I call all of them in parallel I almost instantly get following error:

```
Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:315:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:523:20)
```

If I call those urls in chain with a decent timeout (100ms), requests run through without a problem. I am guessing that ebay has some sort of IP rate limiter in place to protect themselves. I understand that, but I think requestjs should not crash, but rather throw in error.

**Comment by SimonSchick** [comment]
Can you post the code and/or the options used in request?
