### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by Areks** [request/request#2047]
Hi, i know that such issues were created before, but there was a little bit different description.

I tried to perform simple request: send form data. But when i use request module it always throw "socket hang up". 

Below simple test case and results

```
'use strict';

const request = require('request');
const http = require('http');
const querystring = require('querystring');

const data = {
	xstext: 'I have a some problem about node.js server. What should I do to solve the this problem?',
	spintype: 0,
	removeold: 0,
};

// Using request
request(
	{
		method: 'POST',
		url: 'http://address:9017/',
		form: data,
	},
	(error, responce, body) => {
		if (!error) {
			console.log(body, responce);
			return;
		}
		console.log(error);
	}
);

// Using native http
let postData = querystring.stringify(data);

let options = {
	hostname: 'address',
	port: 9017,
	path: '/',
	method: 'POST',
	headers: {
		'Content-Type': 'application/x-www-form-urlencoded',
		'Content-Length': postData.length,
	},
};

let req = http.request(options, (res) => {
	console.log(`STATUS: ${res.statusCode}`);
	console.log(`HEADERS: ${JSON.stringify(res.headers)}`);
	res.setEncoding('utf8');
	res.on('data', (chunk) => {
		console.log(`BODY: ${chunk}`);
	});
	res.on('end', () => {
		console.log('No more data in response.');
	});
});

req.on('error', (e) => {
	console.log(`problem with request: ${e.message}`);
});

req.write(postData);
req.end();

```

For request module:
```
{ [Error: socket hang up] code: 'ECONNRESET' }
```

For native http:
```
STATUS: 200
HEADERS: {"content-length":"98","content-type":"text/html","cache-control":"no-cache","connection":"keep-close"}
BODY: Excellent some problem about client. js server. What must i do to solve the particular this issue?
No more data in response.
```

Loks like it's really bug in request module.

**Comment by swxy** [comment]
I have same problem, but add option `gzip:true` will work.

**Comment by drewfish** [comment]
What version of node.js are you using? We're seeing occasional `ECONNRESET` exceptions after upgrading from 0.10 to 0.12. From digging through the node.js bugs it looks like this might have been broken in 0.12 and fixed afterwards.

**Comment by aymeba** [comment]
Same issue here. Any updates ? I'm using node.js 4.2.2 and I am getting periodic (3-4 times per minute) ECONNRESET error.

**Comment by drewfish** [comment]
Hi @aymeba it looks like the first 4.x version which has this fix is 4.4.0.

Look for commits titled `http: handle errors on idle sockets`. There are a bunch of different commits with this title, since it was applied to different branches.

**Comment by aymeba** [comment]
I don't think that it happens because of the bug you pointed. In our case it appears : 

* Send a request to our backend
* Backend processes the request 
* Somehow the request is disconnecting without waiting the response and we are getting ECONNRESET

I'm confused to get this error because in a usual case, our backend server should throw this error or?

**Comment by juanpablopizarro** [comment]
Any update about this?. I see the error with botkit 0.2.1.

**Comment by gochinj** [comment]
I am having a similar issue.  I have done hours of research, testing and debugging. In my case posting to the same restapi via Postman the end-point works fine.  Making the request via the native NodeJS http.request call fail.  All headers, and payload (body) are the same. (except I don't have the postman-token in the headers)

Full disclosure, I am use restify for my server.

**Comment by frogcjn** [comment]
Same issue here.

**Comment by nsilva** [comment]
In case you using restify on the server side, it would help to enable the auditer, that should provide some hint on what is going on. Also, make sure you are setting the right "Content-Type" in your request so the server knows what to expect. I've seen this error when the server is misunderstanding the request, so providing the content type will help.

**Comment by murali0286** [comment]
Any update on this issue? I still see this issue happening with Node v5.0.0. I see it throws error exactly after 45 secs from the time the request is made.

**Comment by mllanes** [comment]
I have seen this same problem with HapiJS. The issue was a wrong content-length header

**Comment by harvolev** [comment]
I'm seeing this same issue with Node v6.8.1 and using Express
I'm performing a simple https.get request to an API server (which receives and responds with a 200 from the API server)

```
let options = {
                method: 'GET',
                hostname: 'hostname that is resolved correctly',
                path: 'simple path also validated with postman',
                header: {
                    "Authorization": Basic user:pass to base64
                }
            }
```

I'm performing the request as such:

```
const request = https.request(options, (response) => {
    console.log('got a response');
}

request.on('error', (err) => {});

```

This seems like a basic request however I'm getting:

```
{ Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9) code: 'ECONNRESET' }
```

**Comment by roddrec23** [comment]
i want to make a request for a subscription and notification thanks...

**Comment by aiwb** [comment]
happening with Node v6.9.2.


```javascript
  get: async function(ctx) {
    let body = await new Promise(function(resolve, reject) {
      return ctx.req.pipe(request('/path/to/my/backend', function(err, res, body) {
        if (err) { return reject(err) }
        resolve(body)
      }))
    })
    return body
  }
```

**Comment by fractalf** [comment]
+1
Node 6.9.4
request 2.79.0

Works fine with curl
The url I try to get returns header Content-Length

**Comment by illumimari** [comment]
+1
Node 6.9.1
request 2.79.0

**Comment by extensionsapp** [comment]
Wget success, but request - error.

```
# node req.js
REQUEST { uri: 'http://wtfismyip.com', callback: [Function] }
REQUEST make request http://wtfismyip.com/

{ Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
```

**Comment by Vanit** [comment]
Having the same problem. Interestingly it seems to be independent of the request version as the same code works for me in 6.4.0, but breaks in 6.9.2 (these are just the 2 versions I happen to have installed).

**Comment by dieseldjango** [comment]
In my case I was able to workaround the problem by setting the `Connection: keep-alive` header.

**Comment by fractalf** [comment]
@dieseldjango Thanks for the suggestion. Didn't solve my case though.

Here is a site that gives this error, for reproduction:

```
{ request: 
   { debugId: 1,
     uri: 'https://www.deal.no/',
     method: 'GET',
     headers: 
      { Connection: 'keep-alive',
        host: 'www.deal.no',
        'accept-encoding': 'gzip, deflate' } } }
error:  Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1111:19)
    at TLSSocket.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
..using [request-debug](https://github.com/request/request-debug) for debugging the headers sent

**Comment by hamxabaig** [comment]
Isn't this resolved yet? It was working fine like two weeks ago and i'm now getting this error 
`{ [Error: socket hang up] code: 'ECONNRESET', response: undefined }`
node -v 4.4.7

**Comment by aiwb** [comment]
try remove 'accept-encoding': 'gzip, deflate' in the headers solved this.

**Comment by gochinj** [comment]
I see people are getting this error more frequently.  In my case it was really simple.  What I *though* was a properly formed URL based on one of my algorithms, was actually malformed. I encourage all of  you experiencing this issue to assume the problem is in your code. I assure you, in 98% of the cases  the root cause is something mundane  that you are taking for granted or overlooking.  I have tried all of the above to solve the problem, but in the end, it came down to an extra forward slash.

**Comment by kazaff** [comment]
i try to follow all suggest that you say, but this issue does still happen. so sad....

**Comment by Vanit** [comment]
If it helps anyone I eventually worked around the issue by using require('child_process').exec to call curl. Make sure you properly sanitize your inputs if they're coming from userland.

**Comment by itsay** [comment]
Please try request to google.com => hostname: 'google.com'
In my case, "hostname" was handle by nginx as proxy and it does not response when receive request with empty body.
This code get error:
```
var http = require("http");
var options = {
  hostname: 'myAddressNginx',
  port: 80,
  path: '/',
  method: 'GET',
  headers: {
    'Content-Type': 'text/html',
    'Content-Length': Buffer.byteLength("")
  }
};

var req = http.request(options, (res) => {
  res.on('data', (chunk) => {console.log("%s", chunk);});
  res.on('end', () => {});
});

// write data to request body
req.write("");
req.end();
```
This code works
```
var http = require("http");
var options = {
  hostname: 'myAddressNginx',
  port: 80,
  path: '/',
  method: 'GET',
  headers: {
    'Content-Type': 'text/html',
    'Content-Length': Buffer.byteLength("")
  }
};

var req = http.request(options, (res) => {
  res.on('data', (chunk) => {console.log("%s", chunk);});
  res.on('end', () => {});
});

// write data to request body
req.write("abc");
req.end();
```

**Comment by cismous** [comment]
+1
Node 6.9.5

**Comment by vognition** [comment]
Hi Guys, I have the same issue.   +1
Luckily I use 'request' within a 2nd monitoring tool so my issues are minimal.  I like node.js a lot, so I'm posting some feedback.  I hope my feedback helps a little with your attempts to fix the issue. 

The error is now appearing consistently in a high traffic production environments. 
I can spin up an "exact" replica of the server and the error "never" appears.  I can switch endpoints around, and it always ends up the high traffic production environment causes this error for the client.
{ [Error: socket hang up] code: 'ECONNRESET' }.

This began as an intermittent error that I noticed several days ago and after the monitoring service false alarmed too many times.....  and a heck of a lot of times with production test tools that doesn't use 'request' I began searching the web to find this issue here.

Now I have not changed any code/version in over 8 months for this application and am confused to how this can happen out of no where.  So... what changed in the 'request' world if I didn't change any client code?

.........................Now, I'm completely reaching with this next statement.........................
The only other recent thing that I've seen that had any effect on anything is that Sha256 is mandatory out of the CA providers since sometime in 2016.  However, I would have thought that this would appear immediately with a flat stop, unless there is something I'm missing.  Anyway...  a complete reach on that ..

**Comment by BenSower** [comment]
+1
Node 6.9.1

**Comment by aganapan** [comment]
We are also facong same issue with node4 and node6. working fine with node0.12.

**Comment by kunKun-tx** [comment]
it's a node related [issue](https://github.com/nodejs/node/issues/10900#issuecomment-273834289)
see more at [here](https://github.com/nodejs/node/issues/9845#issuecomment-264032107), 


i got caught up and spent the whole afternoon trying to figure it out...
till i saw @fractalf 's example, and realized that all these happened only sites hosted on IIS6 with https

**Comment by aganapan** [comment]
No luck. 

setting ciphers to following didn't work for me.
agentOptions: {
  ciphers: 'DES-CBC3-SHA'
}

**Comment by kunKun-tx** [comment]
@aganapan what's the url you were requesting? My solution will only fix issues related to website hosting on IIS6 + TLS1.0.  There could be other issues that result in similar error msg.

**Comment by danielkhan** [comment]
I had the same problem. I used ngrok and looked at the RAW request. Turned out that there was a e2808b non printable character appended to the user input. Most probably copy/paste. I used `encodeURIComponent()` on that user provided URI part and the problem vanished.

**Comment by rambo-panda** [comment]
I had the same problem. 

* node V6.9.5
* request V2.69.0

@danielkhan I have used the `encodeURIComponent ` method;

```javascript
// this is request
{
    "request": {
        "debugId": 5,
        "uri": "https://xxx.cdn.cn/js/information_main_27d1838a.js",
        "method": "GET",
        "headers": {
            "user-agent": "Mozilla/5.0 (Linux; Android 5.1.1; Nexus 6 Build/LYZ28E) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36",
            "host": "xxx.cdn.cn"
        }
    }
}

{
    "response": {
        "debugId": 5,
        "headers": {
            "expires": "Sat, 15 Apr 2017 11:01:16 GMT",
            "date": "Thu, 16 Mar 2017 11:01:16 GMT",
            "content-type": "application/x-javascript; charset=utf-8",
            "content-length": "49785",
            "last-modified": "Sun, 12 Mar 2017 14:30:49 GMT",
            "cache-control": "max-age=2592000",
            "access-control-allow-origin": "*",
            "accept-ranges": "bytes",
            "age": "19",
            "x-cache": "HIT from www.matocloud.com",
            "connection": "close",
            "alt-svc": "h2=\":443\""
        },
        "statusCode": 200
    }
}
```

**Comment by lhsvobodaj** [comment]
Node.js 6.10.0
request 2.72.0

We found the same issue while running some backend integration tests. Our product connects to several network devices using HTTPS. In this scenario, we are establishing several HTTPS connections and executing some POST and GET requests to each device. 
Since the problem occurred in our test environment, the workaround was to disable the HTTP persistent connections (set HTTP header `Connection: close`). By doing this, we ask the server to close the connection after delivering the response (HTTP/1.1). However, we lose the benefits of HTTP persistent connections since now each TCP will serve only one request.

**Comment by IceMimosa** [comment]
For me, curl is not working. I found i had set proxy to my command line tool before. It works fine now when i remove proxy.

**Comment by akigupta131** [comment]
I am still getting this problem.

```
{ Error: socket hang up
 at createHangUpError (_http_client.js:302:15)
 at Socket.socketOnEnd (_http_client.js:394:23)
 at emitNone (events.js:91:20)
 at Socket.emit (events.js:186:7)
 at endReadableNT (_stream_readable.js:974:12)
 at _combinedTickCallback (internal/process/next_tick.js:74:11)
 at process._tickDomainCallback (internal/process/next_tick.js:122:9) code: 'ECONNRESET' }
```

**Comment by fmikael** [comment]
Finally got this to work for the recaptcha. I had to import and use the https library. Here is the working code: 

var https = require('https');
var querystring = require('querystring');

var secret = "YOUR_KEY";
  var response = RESPONSE_CODE;
  var postData = "secret="+secret+"&"+"response="+response;
  
  // Build the post string from an object
  var post_data = querystring.stringify({
      'compilation_level' : 'ADVANCED_OPTIMIZATIONS',
      'output_format': 'json',
      'output_info': 'compiled_code',
        'warning_level' : 'QUIET',
        'js_code' : postData
  });

  var options = {
    hostname: 'www.google.com',
    port: 443,
    path: '/recaptcha/api/siteverify',
    method: 'POST',
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
        //'content-encoding': 'gzip',
        //'Connection': 'close'
    },
    agentOptions: {
      ciphers: 'DES-CBC3-SHA'
    }    
  };
  var req = https.request(options, function(res) {
    console.log('Status: ' + res.statusCode);
    console.log('Headers: ' + JSON.stringify(res.headers));
    res.setEncoding('utf8');
    res.on('data', function (body) {
      console.log('Body: ' + body);
    });
  });
  req.on('error', function(e) {
    console.log('problem with request: ' + e.message);
  });
  // write data to request body
  req.write(postData);
  req.end();

**Comment by stefanb2** [comment]
**NOTE:** recording this for others who will probably stumble of this discussion when searching the internet for that particular error message.

As it turns out most of the discussion above misses the point, because the error is **not** caused by the client site and hence trying different "workarounds" for `request` will most likely not work. The problem is that the HTTP request socket on the **server side** runs into the idle timeout, because of a long delay in a background operation, and then closes the socket. That results in the ECONNRESET on the client side.

If you are also responsible for the server side source code and use the express/koa framework then you should disable the idle timeout on the HTTP request socket before initiating the long lasting backend operation. E.g. for an ES6 koa route handler:

````javascript
ctx => {
    ....
    ctx.socket.setTimeout(0);
    // now trigger the long lasting backend operation
    ....
}
````

Now my client timeout problem is gone without changing any line in the client code...

**Comment by vdisawar** [comment]
make sure you're calling the url with the right SSL - either https or http

**Comment by qingguo-yu** [comment]
It's also proxy issue in my case. After reset http_proxy and https_proxy, the issue is gone.

**Comment by nickpeleh** [comment]
I had the same issue.

For curl:
` HTTP/1.1 200 OK`

For native http module:
`{ [Error: socket hang up] code: 'ECONNRESET' }`

For request module:
`{ [Error: socket hang up] code: 'ECONNRESET' }`

The reason was in response, particularly in wrong syntax of http protocol.
`\n` symbol was after every header, but must be `\r\n`, and after last header - `\r\n\r\n`.

When it was fixed on backend, the error disappeared.

May be it will will be useful and save time for somebody.

**Comment by poltorina** [comment]
I had the same problem. In my case I set User-Agent in headers in request options and problem is gone.

**Comment by amejiarosario** [comment]
Having the same issue with Node 8.x

**Comment by rambo-panda** [comment]
+1
Node 8.1.2
"request": "=2.81.0"

```javascript
{
    "method": "GET",
    "json": true,
    "uri": "http://www.bb.com/xxxxxxxxxxx",
    "baseUrl": null,
    "headers": {
        "cookie": "yyyyy",
        "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60"
    },
    "qs": {
        "app_version": "1.9.8.8",
        "env": "prod"
    }
}

//res
Error: socket hang up
InternalServerError: Internal Server Error

// setting
var _request = require('request').defaults({
		forever      : true,
		maxRedirects : 8
	}),
```

**Comment by datanglibai** [comment]
I got the same error, but a little bit different, my situation is like this.
testapp -> api A -> api B
-> means request
test app get the hang up error when A request B very slowly and finally get an 500 error from B (the error is handled in api A).
I'm sure it's not a time out issue, since api A do a lot of things and always return response very slow, but no error.
Now i'm really confused how the express and request works, the 500 error is already handled by api A and has other actions follow up. why the test app will still get socket hang up error?

**Comment by jpollard-cs** [comment]
I'm also running into this issue in the latest node (8.6) as well as with the latest 7.x release. Details are here if anyone wants to take a stab at it: https://stackoverflow.com/questions/46666079/node-js-http-get-econnreset-error-on-read

Please let me know if I can provide any additional information!

**Comment by ramziraissi** [comment]
Having the same issue with Node 6.10.0

**Comment by naugtur** [comment]
Another possible explanation: you are sending more data in HTTP body than specified in Content-Length header

**Comment by jsmonkey** [comment]
+1
Node 8.6.0

**Comment by ramziraissi** [comment]
To fix the issue you should:
1-Add process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
2-Upgrade zone.js to v0.7.4

**Comment by jonnycoder1** [comment]
I had the same problem and the resolution was to use environment variable NO_PROXY="yourcompany.com" as well as strictSSL:false, as our request was being made to internal company url and was attempting to use proxy server. You can use process.env.NO_PROXY="yourcompany.com" programmatically.

**Comment by illya13** [comment]
+1, node 8.8.1
```
at createHangUpError (_http_client.js:329:15)
at Socket.socketOnEnd (_http_client.js:421:23)
at emitNone (events.js:110:20)
at Socket.emit (events.js:207:7)
at endReadableNT (_stream_readable.js:1056:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9) code: 'ECONNRESET' }
```

**Comment by jpollard-cs** [comment]
appears the issue on my end was that Vagrant was "occupying" the port and sending a TCP packet with a `FIN` flag immediately following my `GET` request although it's still unclear why chrome and postman had no problem working around this - perhaps they have some added resilience

**Comment by dotbloup** [comment]
I had this problem, GZIP was on, Keep alive was on too. 
The problem vanished after adding packages.

```
const zlib = require('zlib'); // for GZIP
const http = require('http');
const https = require('https');
```

**Comment by markbarton** [comment]
Same problem - fixed by changing the URL from localhost to the actual IP of the host machine just a FYI

**Comment by tsirolnik** [comment]
Still having this issue.... No apparent reason.

```js
info:  Error: socket hang up
    at createHangUpError (_http_client.js:345:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by renminghao** [comment]
hi， I do not know if you solved this problem yet， but I had solved this tody, when I debug, I find, 
```
// Using native http
let postData = querystring.stringify(data);
...
req.write(postData);
```
if you remote server is start by koa(or another nodejs server), and the data is `{}`, the `postData` by stringify function transform to `{}`, but the koa server get the `{}` will throw the `parser error`, so this request will throw error by 
```
Error: socket hang up
    at createHangUpError (_http_client.js:345:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```
so I had do this : __postData = postData === '{}' ? '' : postData__

hope it's can help you

**Comment by LvChengbin** [comment]
For me, this is happening while sending a `POST` request with `content-length : 0` in the request headers. I don't know if this result is reasonable, but at least I think maybe you can try removing each item in headers you added to find out the reason for the problem.

**Comment by chandler0415** [comment]
when i change 'GET' to 'POST', fix it. but dont know why, i fix it from https://cnodejs.org/topic/57a6c35282e6ea4870ecd3f2, someone said if you use 'GET', the code cant run `res.on('data', cb)`

**Comment by ahmedfouzan** [comment]
@LvChengbin I was also facing the same problem on `POST` request. Replacing `Content-Length : 0 `with actual length of the worked for me.

**Comment by lfreneda** [comment]
Somebody save me :angel:

**Comment by YeDongaidiiqu** [comment]
I have also the same problem in bode v.8.9

{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNR
ESET' }

my code is below.


let request=require("request");
 request({
        url: "http://192.168.31.29:3019/tactics/createMediaHotTotal20",
        method: "GET",
        json: true,
        headers: {
          "content-type": "application/json"
        },
      }, function (error, response, body) {
        if (error) {
         console.log(error)
        } else {
          resolve(body);
        }
      })

**Comment by gkatsanos** [comment]
Same issue, latest node 9.x
```js
const https = require("https");
const fs = require("fs");

process.env.NO_PROXY="yourcompany.com";

const options = {
  hostname: "en.wikipedia.org",
  port: 443,
  path: "/wiki/George_Washingtons",
  method: "POST",
  // ciphers: 'DES-CBC3-SHA'
};

const req = https.request(options, (res) => {
  let responseBody = "";
  console.log("Response started");
  console.log(`Server Status: ${res.statusCode} `);
  console.log(res.headers);
  res.setEncoding("UTF-8");
  
  res.once("data", (chunk) => {
    console.log(chunk);
  });
  
  res.on("data", (chunk) => {
    console.log(`--chunk-- ${chunk.length}`);
    responseBody += chunk;
  });
  
  res.on("end", () => {
    fs.writeFile("gw.html", responseBody, (err) => {
      if (err) throw err;
      console.log("Downloaded file");
    });
  });
});

req.on("error", (err) => {
  console.log("Request problem", err);
});
```
```
Request problem { Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at TLSSocket.socketOnEnd (_http_client.js:423:23)
    at TLSSocket.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19) code: 'ECONNRESET' }
```

**Comment by ablade** [comment]
I have the same bug.  The POST works when Content-Length is added to the request.  Hope this helps you guys:
'Content-Length': Buffer.byteLength(data) //Content-Length is needed for a POST

**Comment by Gormartsen** [comment]
I dig it a little bit.
I have a rear once in a week issue with request when send POST to nodejs server.
After going dipper, I found that nodejs just hang connection if request is malformed.

Looks like some rear bug happens when POST request get passed into http.request

**Comment by and-kost** [comment]
Using 'http' instead of 'https' protocol solve the issue too.

**Comment by cactusme** [comment]
This is very frustrating.  I don't have control over the server but I can't do POST from Nodejs (using request or superagent), but can do curl or Postman successfully.  Even crazier, the call would succeed if I pause using debugger on the request statement, and continue.

**Comment by wjsilva85** [comment]
In my case just removed the 'Host' header, solved.

**Comment by davoam** [comment]
We ran into this issue after upgrading to a newer nodejs (`10.16.3`). On client side we used nodejs http agent with `keepAlive: true`. It looks like the following happened: 
- client uses free socket to do a request
- in the same time server closes the socket because of [keepAliveTimeout setting](https://nodejs.org/api/http.html#http_server_keepalivetimeout) which has appeared in nodejs version 8

Almost the same problem described [here](https://github.com/request/request/issues/2047).

**Solution**
So far we've found two solutions:
1) On the server side disable `keepAliveTimeout` by setting it equal to `0`
2) Close free sockets in less than `keepAliveTimeout` value (by default it 5 seconds). The default http agent does not support such a capability (`timeout` setting does not do it). So we used (agentkeepalive)[https://github.com/node-modules/agentkeepalive#readme] lib

**Comment by sadller** [comment]
```
let req = http.get(options, (res) => {
    ...........
    ...........
});
```

Try this.

**Comment by jainmnsh** [comment]
We are facing a similar issue - currently, we are using 6.11.x but we tried node 10 but does not help.

We even tried upgrading request module  + adding all suggestions provided but no help.

Any other ideas or help in troubleshooting.

**Comment by jainmnsh** [comment]
we are able to resolve this issue - our API gateway had a timeout setting that causing this issue. thanks for looking into it.

**Comment by dzz9143** [comment]
> we are able to resolve this issue - our API gateway had a timeout setting that causing this issue. thanks for looking into it.

Hi, can you tell me what kind of timeout setting lead to this problem

**Comment by dudvil1** [comment]
i have the same issue when i'm testing my routes with chai-http. the absurd is that the first three pass ok!! i'm try to face it all day

here my code: 
 ```
log("working test")
 it("test the /login routes", done => {
    chai
      .request(server)
      .post("/login")
      .send({ })
      .end(function(err, res) {
        expect(err).to.be.null;
        expect(res.status).to.not.equal(404);
        expect(res.body.message).to.not.be.equal("Not Found");
        done();
      });
  });

log(fail test with Error: socket hang up)
  it('test the /getResetCodePassword route', (done)=> {
    chai
      .request(server)
      .patch("/getResetCodePassword")
      .send({ })
      .end( (err,res) => { 
        console.log(err);
        done();
      })
  })

```

**Comment by PLQin** [comment]
I used 'http.request', but forgot to call '.end(); 'Method;
When I add '.end (); '   , after the method, the problem is solved!

---

In addition, 'Content-Length' should not be added randomly;
Here's all of my code: 

```
const http = require('http')
const querystring = require('querystring');

/**
 * 给短信中心发出要求发送验证码的请求
 * 
 * @param {*} res 
 * @param {*} params 
 */
module.exports = (query) => {
  const { mobile, content } = query;

  return new Promise((resolve, reject) => {
    const postData = querystring.stringify({
      'receive': '22211w',
      'tag': '123456',
      'templateId': 'M09DD535F4'
    });
    const options = {
      hostname: 'sms.google.com',
      port: 80,
      path: `/sms/send?${postData}`,
      method: 'POST',
      timeout: 5000,
      headers: {
        'Authorization': 'APPCODE 2080cf555ecb43c188f01f5010dc9d70'
      }
    };

    const req = http.request(options, res => {
      let data = '';
      res.on('data', (chunk) => {
        data += chunk;
      });
      res.on('end', (d) => {
        resolve(data)
      });
    })

    req.on('error', (err) => {
      console.error(`SMS ERROR : ----------------------------`);
      console.error(err);

      reject(err)
    })

    req.end();

  })
}
```

**Comment by makingglitches** [comment]
I'm getting this when i use pipe() and the connection goes away.
there is no way of calling .catch() inline to create a promise tree.
catch() resolves to a class called "Bluebird", so pipe doesn't exist.
also unsure if there would be a race condition if I call...

var res = request.get()
then res.catch()
then res.pipe(stream);

**Comment by makingglitches** [comment]
This is kind of important for retry logic.

**Comment by makingglitches** [comment]
Apparently looking at the issue #3372 comment I made, you can actually handle this in the on('error',function(){}) event handler.

If you await this function you can also enclose the entire thing in a try-catch block.

This is actually an annoying thing to diagnose, since the issue is caused by internet connection problems.

**Comment by melroy89** [comment]
Still having this issue: https://github.com/lbry-foss/lbry-desktop/runs/4692765872?check_suite_focus=true#step:6:207

Maybe we are hitting a time-out?

* Did you check for setting `keepAlive: true` in the http agent?
* Did you have `res.end()`?

**Comment by baparham** [comment]
I have these observations from trying to debug this locally:

1. we never enter the `if` block where `overwriteArtifact` is called
2. the description we get back from github is not json, but plain text, so the `e.description.errors[0].code` in the if statement is undefined since `e.description` has not been parsed into an object.
3. I do not believe this is the entirety of this problem, since I continue to _also_ hit 502 bad gateway or other econnreset errors sometimes alongside, however this may be the root cause of the "can't overwrite an already created draft release asset" problem

I'll continue experimenting and debugging, and try and come up with a PR to fix at least this portion of these errors

**Comment by zhou-1** [comment]
Met the same issue in https.get() method; tried all methods but failed.

The issue disappeared when I switched the branch to another and then switch back...

**Comment by makingglitches** [comment]
> Still having this issue: https://github.com/lbry-foss/lbry-desktop/runs/4692765872?check_suite_focus=true#step:6:207
> 
> Maybe we are hitting a time-out?
> 
> * Did you check for setting `keepAlive: true` in the http agent?
> * Did you have `res.end()`?

just a drunken contribution. is javascript always so hard to assess the issue in ?
I swear this error just bubbled up from some hidden layer I can never trace to on my end ! very frustrating !

**Comment by paulofreiredev** [comment]
> accept-encoding

This works for me, thank you!
edit: I was wrong, I just removed the `Host` header, and I received an 400, that in my case, should be the right error code, but, when i try to call another endpoint, as a get, that I used to receive 200, I received 400 instead.
