### ISSUE TITLE
It's possible to abort a non-started request

### ISSUE THREAD

**Issue by partycoder** [request/request#2065]
I am getting an exception like this:

```
TypeError: Cannot call method 'end' of undefined
at Request.end (node_modules/request/request.js:1372:12)
at Request.destroy (node_modules/request/request.js:1393:10)
at IncomingMessage.onclose (stream.js:87:50)
at IncomingMessage.emit (events.js:117:20)
at abortIncoming (http.js:1917:11)
at CleartextStream.serverSocketCloseListener (http.js:1928:5)
at CleartextStream.emit (events.js:117:20)
at tls.js:694:10
at process._tickDomainCallback (node.js:486:13)
```

So, by reading the code here:
```javascript
Request.prototype.end = function (chunk) {
  ...
  if (!self._started) {
    self.start()
  }
  self.req.end()  // here
}
```
`end` will guard itself from not being started by using the `_started` flag.
however `start` won't do anything if `_aborted` is true.
and `abort` doesn't use `_started`, we end up with:

1. aborted a non-started request
2. destroy is called
3. end is called
4. end will call start
5. start won't do anything because it was aborted
6. end will crash because it wasn't started.

I will workaround this on my code by only calling `abort()` if `_started` is `true` unless you have a better idea.

**Comment by arboreal84** [comment]
Just for the record, the workaround to this problem is to wrap `req.abort()` in the following manner:
```
   if (req._started === true) {
       req.abort();
   }
```
