### ISSUE TITLE
Tor example with agentOptions breaks when hitting URL with https

### ISSUE THREAD

**Issue by joshterrill** [request/request#2084]
I am trying to use `request` with `roboto` to crawl onion links. However when I setup request to use tor as a proxy, I get this error when it encounters a URL that is https.

```
Error: Protocol "https:" not supported. Expected "http:".
    at new ClientRequest (_http_client.js:53:11)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:163:15)
    at Request.start (/var/www/crawl/node_modules/request/request.js:747:30)
    at Request.end (/var/www/crawl/node_modules/request/request.js:1381:10)
    at end (/var/www/crawl/node_modules/request/request.js:575:14)
    at Immediate._onImmediate (/var/www/crawl/node_modules/request/request.js:589:7)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

As per the `roboto` docs, my implementation of this is:

```
var myDownloader = function(href, requestHandler) {
  var requestOptions = _.extend(this.defaultRequestOptions, {
    url: href,
    agentClass: Agent,
    agentOptions: {
        socksHost: 'localhost', // Defaults to 'localhost'.
        socksPort: 9050 // Defaults to 1080.
    }
  });

  request(requestOptions, requestHandler);
};

fooCrawler.downloader(myDownloader);
```

Anyone know how to get around this?

**Comment by joshterrill** [comment]
Nevermind, I just found the answer: https://github.com/mattcg/socks5-https-client
