### ISSUE TITLE
When pfx passphrase is worng.

### ISSUE THREAD

**Issue by jaoxico** [request/request#2155]
When I try to connect using pfx file and gives it a wrong passphrase, it gives me the error bellow:

/home/joao.souza/e-financeira/node/node_modules/request/request.js:1383
  self.req.end()
          ^

TypeError: Cannot read property 'end' of undefined
    at Request.end (/home/joao.souza/e-financeira/node/node_modules/request/request.js:1383:11)
    at end (/home/joao.souza/e-financeira/node/node_modules/request/request.js:575:14)
    at Immediate._onImmediate (/home/joao.souza/e-financeira/node/node_modules/request/request.js:589:7)
    at processImmediate [as _immediateCallback](timers.js:383:17)

As soon as I commented that line it worked like a charm.

**Comment by nokka** [comment]
I also get an error when the pfx password is wrong, but I end up in the on('error') handler as expected, but an uncaught exception is still thrown in the request lib, here's the error.

TypeError: Cannot read property 'write' of undefined
    at Request.write (/Users/stekon/Projects/pf/node_modules/request/request.js:1385:18)

The line is very close to the one you're describing. 1385 and 1383.

**Comment by jaoxico** [comment]
I've solved that executing openssl with typed passphrase to check before send that to soap.
