### ISSUE TITLE
Can't require request library inside routes folder in an express project.

### ISSUE THREAD

**Issue by echavezNS** [request/request#2193]
I have an express project and something weird is happening, I have  `var request = require('request');` inside the routes/index.js file and it doesn't work, it throw me this error:

``` shell
module.js:341
    throw err;
    ^

Error: Cannot find module './lib/helpers'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/echavez/Development/mentionapp/node_modules/request/index.js:19:29)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
[nodemon] app crashed - waiting for file changes before starting...
```

Can somebody tell me if how can I fix this?

Thank's.

**Comment by simov** [comment]
There is something wrong with your setup or/and installation. Try to re-install everything.
