### ISSUE TITLE
incorrect header check when deal with deflate content encoding

### ISSUE THREAD

**Issue by goorockey** [request/request#2197]
```js
var rq = require('request');
rq.get('https://web.wechat.com', {gzip: true});

Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:370:17)
```

While the response from https://web.wechat.com is in deflate format, it show this error.
According to PR #2172, request library support deflate content encoding.

After I change `responseContent = zlib.createInflate()` to `responseContent = zlib.createInflateRaw()` in request.js, it work fine.

**Comment by simov** [comment]
That's interesting, it looks like our implementation is too optimistic. The only possible solution that I can think of is to peek into the stream and check if the `zlib` headers are present, then switch to either `createInflate` or `createInflateRaw`.

**Comment by windbender** [comment]
FWIW  I found this precise error when trying to use  tar.gz  to decompress  a x.tar.gz  file created on an OS X machine


```
octogon:tmp lumigrow$ targz e ver1.tar.gz .
/usr/local/lib/node_modules/tar.gz/bin/targz:18
        throw err;
        ^
Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:370:17)
```

The file is attached

[ver1.tar.gz](https://github.com/request/request/files/320910/ver1.tar.gz)

**Comment by adampash** [comment]
Fwiw, I was running into the same error, and the @czardoz branch fixed it for me. (Thanks @czardoz!)

**Comment by umutm** [comment]
We also experience the same issue for some websites. Is there a planned official fix for that?

**Comment by gotojmp** [comment]
waiting for fix.

**Comment by mfrye** [comment]
I came across this on something unrelated, but @czardoz has a legit fix. It seems like that code should be apart of zlib right? To auto detect instances like that.

**Comment by thesadabc** [comment]
waiting for fix

**Comment by ali-habibzadeh** [comment]
waiting for fix

**Comment by mweathers** [comment]
waiting for fix

**Comment by rogierslag** [comment]
I'd also love a fix for this. http://www.mars.com/uk/en/careers/graduates-students/our-programmes/european-finance-development-programme is encountering the same problem

**Comment by goddkiller** [comment]
another method to avoid this problem is to set Accept-Encoding: gzip. 
tell the server that you only use gzip.

**Comment by jiangts** [comment]
Why isn't the @czardoz branch getting submitted as a PR for merging?

**Comment by nebulousdog** [comment]
looks like this issue is still happening? I think via my `jsdom` dependency that requires `request`.
