### ISSUE TITLE
Cannot read property 'emit' of null

### ISSUE THREAD

**Issue by djphoenix** [request/request#2226]
Sometimes when making a lot of requests I catching this error:
```
.../node_modules/request/request.js:83
    socket._httpMessage.emit('error', error)
                       ^

TypeError: Cannot read property 'emit' of null
    at TLSSocket.connectionErrorHandler (.../node_modules/request/request.js:83:24)
    at TLSSocket.g (events.js:286:16)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
Code of request creation:
```js
const request = require('request').defaults({
  baseUrl: api_endpoint,
  method: 'POST',
  json: true,
  gzip: true,
  forever: true,
  timeout: 15000,
});
// ....... //
function api(method, params, token) {
  return new Promise((res,rej)=>{
    var retries = 0;
    const retry = ()=>{
      retries++;
      request({
        uri: method,
        form: params,
      }, (err, resp, body)=>{
        if (err && retries < 5) {
          setTimeout(retry, 500);
        } else if (err) {
          rej(err);
        } else if (body.response != undefined) {
          res(body.response);
        } else if (body.error != undefined) {
          rej(body.error);
        } else {
          rej("Unknown API error");
        }
      });
    };
    retry();
  });
}
```

**Comment by zarenner** [comment]
Duplicate of #1903?

**Comment by djphoenix** [comment]
Yes, not found this before. Thx for upstream.
