### ISSUE TITLE
PEM_read_bio:no start line

### ISSUE THREAD

**Issue by goliatone** [request/request#2233]
I'm getting the following error:

```
error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Object.createSecureContext (_tls_common.js:88:19)
    at Object.exports.connect (_tls_wrap.js:997:48)
    at Agent.createConnection (https.js:82:22)
    at Agent.createSocket (_http_agent.js:182:26)
    at Agent.addRequest (_http_agent.js:144:10)
    at new ClientRequest (_http_client.js:158:16)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:199:15)
    at Request.start (.../node_modules/request/request.js:753:32)
```

using both node v0.12.4 and v6.2.0.
request v2.72.0

If I switch to a random lib to perform the POST, it goes through.  Using [post-json](https://www.npmjs.com/package/post-json)

**Comment by diegoaguilar** [comment]
Were you able to cope this?

**Comment by skyfall174** [comment]
Check this issue, its help me to fix the same problem
https://github.com/request/request/issues/1555#issuecomment-100842751
