### ISSUE TITLE
TypeError: Cannot read property 'emit' of null

### ISSUE THREAD

**Issue by michaelBenin** [request/request#2241]
I'm currently scraping the web heavily with many concurrent requests. 

Many time when I'm on a slow connection I will get this error:

```
/Users/mbenin/Desktop/linkwaylive-etl/node_modules/request/request.js:83
    socket._httpMessage.emit('error', error)
                       ^
TypeError: Cannot read property 'emit' of null
    at Socket.connectionErrorHandler (/Users/mbenin/Desktop/linkwaylive-etl/node_modules/request/request.js:83:24)
    at Socket.g (events.js:273:16)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at emitErrorNT (net.js:1246:8)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickDomainCallback (node.js:430:17)
```

I've patched that line with a check to see if that exists, which has worked. Should I make a pr? 

Thanks!

**Comment by brphelps** [comment]
I believe one of these issues covers this issue: #1903 or #2028 . I would pile onto these :).
