### ISSUE TITLE
Parse Error on some websites

### ISSUE THREAD

**Issue by umutm** [request/request#2243]
When I try to send a HTTP request to http://www.thestartv.com/

I get:
Timeout: Error------Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:309:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)------Parse Error

Tried with Node v4.4.2 and v0.10.27.

On the other hand, many web-based tools that allow sending requests can reach the site fine.

Any ideas "where the problem is"? Thanks very much.

**Comment by Lapsec** [comment]
i had met the same problem

**Comment by Vikaton** [comment]
Same :/ with amazon's alexa voice service api
