### ISSUE TITLE
Problem with  " cannot find module 'tough-cookie' "

### ISSUE THREAD

**Issue by tecnicoEA** [request/request#2290]
Hello! When I include in my server "var request = require('request');" I have the next message:

Error: Cannot find module 'tough-cookie'
at Function.Module._resolveFilename (module.js 338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js 364:17)
at require (module.js:380:17)
at Object.<anonymous> (/home/pi/node_modules/request/lib/cookies.js:313)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function:Module._load (module.js:312:12)
at Module.require (module.js:364:17)

I tested with several versions of node.js and the result is the same. Somebody know what will be happend and how can I solve it? 
Thanks in advance.

Best regards!!

**Comment by qmm-g-Excellent** [comment]
you can delete  node_modules directory and try running **npm  install** again .
