### ISSUE TITLE
self.start invoked when request failed.

### ISSUE THREAD

**Issue by calidion** [request/request#2315]
```
TypeError: self.start is not a function
  at Socket.Request.write [as _write] (/node_modules/request/request.js:1380:10)
  at doWrite (_stream_writable.js:300:12)
  at clearBuffer (_stream_writable.js:407:7)
  at Socket.Writable.uncork (_stream_writable.js:237:7)
  at ClientRequest._flushOutput (_http_outgoing.js:673:10)
  at ClientRequest.OutgoingMessage._flush (_http_outgoing.js:647:16)
  at _http_client.js:156:10
  at callSocketMethod (_http_client.js:531:7)
  at ClientRequest.onSocket (_http_client.js:536:7)
  at ClientRequest.g (events.js:260:16)
  at emitOne (events.js:82:20)
  at ClientRequest.emit (events.js:169:7)
  at tickOnSocket (_http_client.js:502:7)
  at onSocketNT (_http_client.js:514:5)
  at nextTickCallbackWith2Args (node.js:442:9)
  at process._tickDomainCallback (node.js:397:17)
```

**Comment by w446108264** [comment]
Did you solve it？

**Comment by w446108264** [comment]
I use "request": "^2.74.0" on the my main project, but a lib which use "request": "^2.69.0". it's not ok. catch like that TypeError: self.start is not a function.

so i fork the lib and modify as "request": "^2.74.0" , it works 😂

**Comment by calidion** [comment]
when will this be solved?!

**Comment by calidion** [comment]
@w446108264 
I don't have that luck.
all my modules dependent on this module are ruined.
none of then is able to work properly.

**Comment by w446108264** [comment]
😭

开始搜索到这里，以为是个外国人，刚好把问题解决了，就回复一下，没想到你讲中文。

更没想到的是，导致我项目问题的那个lib仓库是你的。
https://github.com/node-weixin/node-weixin-message

https://github.com/node-weixin/node-weixin-message/blob/master/package.json
可见"request": "^2.69.0"   我把他修改为 2.74.0，并暂时删除"node-weixin-request": "^0.4.0"等

项目的问题暂时解决了。本来打算pull request的，因为解决的粗糙还没动手。
见(https://github.com/w446108264/node-weixin-message),

另外node-weixin-message部分方法已经过时了，微信企业号现在似乎（刚接触微信玩法）把内容都加密为Encrypt。
https://github.com/node-weixin/node-weixin-message/blob/master/lib/incoming.js
原来方法

```js

module.exports = {
  on: ons,
  onXML: function(xml) {
    var self = this;
    var preArg = arguments;
    x2j.parseString(xml, {
      explicitArray: false,
      ignoreAttrs: true
    }, function(error, json) {
      if (error) {
        throw Error('Failed Parsing XML!');
      }
      var args = [json.xml];
      for (var i = 1; i < preArg.length; i++) {
        args.push(preArg[i]);
      }
      self.parse.apply(self, args);
    });
  },

```

我简单处理了一下

```js

/**
 * parse -> decrypt -> deliver
 * @param xml
 * @param req
 * @param cb
 */
exports.xmlParse = function (xml, req, cb) {

    // TODO test data
    // xml = "<xml><ToUserName><![CDATA[toUser]]></ToUserName><Encrypt>OuNcGohZgD8y9y70RlXcoPQNblb40chj6bbagCoGa7z7g/qVEhMvdj3d4rkjKcRWeN+YawtrNVCaTBKcOyq57uAQrtrrt7FJp2kQlxneXp4ZTrla8aIAClRIpOQLmq5aoGiCVq9PsALpE70M/SOOjhxlwvKW2YcFjCjEdfuLWGwsJ1zaGBOeAy/pfDwM6xYKYnQ2UFLvsgfoOiRikwuQ5eYsiW5/v6p3mOwc7CCSah7gjV3Z37zU2oFifwJ8Ji50Dletq44tWuFIvShG+e5n1l3yeqsWaHcSYgLavawI0loOJL+vqc1cZRymM9sTN3anvI+OJH09NQeQJLZif/rKAgtnZPaKCNx79Zk29PVBRwTm2YAdfkTTzOd3uq0mP0GtOuZ96swXWs5bFehLbN58yIiwmoaZFrw86m1r/MIUpbiPAEdDLQFzjZe0Mj64CxFIp+8p5ibDfzk3f4rzA08idw==</Encrypt><AgentID>1</AgentID></xml>"


    if(xml == null) {
        log.error("xml can't be null!");
        cb("xml can't be null!");
        return;
    }

    var self = messages;
    var preArg = arguments;

    /**
     * parse
     */
    x2j.parseString(xml, {
        explicitArray: false,
        ignoreAttrs: true
    }, function (error, json) {
        if (error) {
            log.error(error + "  json:" + json);
            cb(error);
            return;
        }
        log.info(json);

        /**
         * decrypt
         */
        var encrypt = json.xml.Encrypt;
        if(encrypt == null) {
            log.error("encrypt can't be null!");
            cb("encrypt can't be null!");
            return;
        }
        var encrypted = nodeWeixinCrypto.decrypt(encrypt, callbackCheckConfig);

        /**
         * parse again
         */
        x2j.parseString(encrypted, {
            explicitArray: false,
            ignoreAttrs: true
        }, function (error, json) {
            if (error) {
                log.error(error + "  json:" + json);
                cb(error);
                return;
            }
            log.info(json);

            var args = [json.xml];
            for (var i = 1; i < preArg.length; i++) {
                args.push(preArg[i]);
            }

            /**
             * deliver
             */
            new rec_event().register(messages);
            new rec_msg().register(messages);
            self.parse.apply(self, args);
        });
    });
};

```


只能说世界真奇妙

**Comment by calidion** [comment]
在我这里升级版本没有用。原因可能跟npm有关系。之前并没有问题。
node-weixin-message欢迎PR。
我对Request提供了一个PR，但是因为很难写测试用例，所以他们还没有集成进去。
request的代码写的也很糟糕。
我已经针对这个bug发布了一个requestx.

**Comment by w446108264** [comment]
短期内没时间pr了。

之前并没有问题，可能是npm的原因，也有没有可能是后面引入其他版本的request。

多版本兼容的问题。

request无论是单独使用2.69.0 还是单独2.74.0在我这边都没有问题

**Comment by calidion** [comment]
new occurrence:
https://travis-ci.org/t1bao/t1bao-weixin/jobs/166577916

Is there anyone who can look into this?

**Comment by FredKSchott** [comment]
It looks like `Request.prototype.write` is being called in the wrong context, and is not properly bound to a `Request` object instance. The request library is not doing this anywhere, so it may be a library built on top of request that is passing the `write` callback improperly without binding it.

If anyone can track it down I would welcome a PR, but I believe that some library is using request incorrectly. If you share what library you are using that gives you this error you may be able to track it down better.
