### ISSUE TITLE
Problem with https

### ISSUE THREAD

**Issue by kivervinicius** [request/request#2319]
On access url https://www.receita.fazenda.gov.br/Aplicacoes/SSL/ATCTA/CPF/ConsultaPublica.asp cause error below:

{ Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }

**Comment by kivervinicius** [comment]
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

before call request.
