### ISSUE TITLE
fails to load the page

### ISSUE THREAD

**Issue by Laptinius** [request/request#2332]
```
request({
  url:'http://xn-----6kcaghakfhqg8a3dbbmjj40a.xn--p1ai/', 
  timeout: 10000
}, function(error, response, body){
  if (error) {
    console.log('error');
    //...
  }
  console.log('load');
  //....
});
```

```
buffer.js:528
    throw new Error('"toString()" failed');
    ^

Error: "toString()" failed
    at Buffer.toString (buffer.js:528:11)
    at BufferList.toString (D:\work\projects\nodejs\v1\node_modules\bl\bl.js:178:33)
    at Request.<anonymous> (D:\work\projects\nodejs\v1\node_modules\request\request.js:1019:32)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\work\projects\nodejs\v1\node_modules\request\request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

site produces an endless file that is loaded for a long time
Why does not {timeut:10000}?

nodejs: v6.1.0
request: v3.8.6

**Comment by boristhuy** [comment]
It would be easier to pinpoint the exact issue if you included more of your code ...
