### ISSUE TITLE
TypeError: Cannot read property 'connectTimeoutTimer' of undefined

### ISSUE THREAD

**Issue by talyuk** [request/request#2357]
I got this error when running simple code (node v6.5.0):
```js
request('http://google.com/', function (error, response, body) {
    console.log(error);
    console.log(response);
});
```
Full text of the error looks like this:
> TypeError: Cannot read property 'connectTimeoutTimer' of undefined
    at ConnectTimeoutAgent.createSocket (/Users/hard/Dev/node-test/node_modules/preq/index.js:21:46)
    at ConnectTimeoutAgent.Agent.addRequest (_http_agent.js:149:10)
    at new ClientRequest (_http_client.js:158:16)
    at Object.exports.request (http.js:31:10)
    at Request.start (/Users/hard/Dev/node-test/node_modules/request/request.js:740:32)
    at Request.end (/Users/hard/Dev/node-test/node_modules/request/request.js:1394:10)
    at end (/Users/hard/Dev/node-test/node_modules/request/request.js:567:14)
    at Immediate.<anonymous> (/Users/hard/Dev/node-test/node_modules/request/request.js:581:7)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

**Comment by scotttrinh** [comment]
Are you using `request` directly? From your stack trace, it appears that you're using `preq`?
