### ISSUE TITLE
Error: Authentication failed at WebSocket.websocket.onClose(

### ISSUE THREAD

**Issue by razorrider7** [request/request#2365]
Whenever I try to connect to inara.cz/cmdr/1 it gives me the error
`Error: Authentication failed
    at WebSocket.websocket.onclose (C:\Users\Christopher\Desktop\Node.js\Adle's Armada Bot\node_modules\discord.js\lib\Client\InternalClient.js:93:1406)
    at WebSocket.onClose (C:\Users\Christopher\Desktop\Node.js\Adle's Armada Bot\node_modules\ws\lib\WebSocket.js:446:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.cleanupWebsocketResources (C:\Users\Christopher\Desktop\Node.js\Adle's Armada Bot\node_modules\ws\lib\WebSocket.js:950:8)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

I am sorry if this has been asked before, but I have no idea as to what to do... my code is [here](https://pastiebin.com/57d6ac156b9ce#)

**Comment by razorrider7** [comment]
Nevermind, figured out something else was doing this... I made a stupid mistake xD
