### ISSUE TITLE
TypeError: source.on is not a function

### ISSUE THREAD

**Issue by kuba-orlik** [request/request#2366]
```
return rp.post({
	url: uri("collections/people"),
	formData: [{a: 1}, {a: 2}],
});

```

I'm trying to POST an array of values to a HTTP endpoint, and this is the error I receive:

```
TypeError: source.on is not a function
    at Function.DelayedStream.create (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/combined-stream/lib/combined_stream.js:43:37)
    at FormData.append (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/form-data/lib/form_data.js:68:3)
    at appendFormValue (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/request/request.js:328:21)
    at Request.init (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/request/request.js:339:11)
    at Request.RP$initInterceptor [as init] (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/request-promise-core/configure/request2.js:45:29)
    at new Request (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/request/request.js:129:8)
    at request (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/request/index.js:55:10)
    at Function.post (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/request/index.js:63:12)
    at /home/kuba/projects/sealcode/sealious/integration-tests/test.js:45:13
    at tryCatcher (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/kuba/projects/sealcode/sealious/integration-tests/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

Are arrays not allowed in formData?

**Comment by ritika-s** [comment]
nope, formData has to be an object. ran into this problem myself :)

**Comment by saeidalidadi** [comment]
I tried to post something like this
```
formData = {
  name: { first: 'Saeid', last: 'Alidadi' }
}
``` 
and got this error also

**Comment by VijayakumarManickam** [comment]
formData accepts only three types of elements viz. string, Buffer and Stream, so try this:
    formData = {
      name: JSON.stringify( { first: 'Saeid', last: 'Alidadi' } )
    }

**Comment by jgonz188** [comment]
Also receiving the same issue. My formData is:

{ 'subscriptions': [  {  "subscription": subscriptionId, "quantity": newQty, "product": product, "prorate": true }           ] }

**Comment by abhiCR7** [comment]
everything needs to be stringified inside formData. try:
`return rp.post({
    url: uri("collections/people"),
    formData: JSON.stringify([{a: 1}, {a: 2}]),
});
`

**Comment by thehappycoder** [comment]
@abhiCR7 Not everything. The rule is that values of formData object can only by any of these: string, Buffer, Stream. @VijayakumarManickam is right.

In my case I had change:
```
formData: {
        variables: {
          file: fs.createReadStream('./assets/car.jpg')
        }
      }
```
to
```
formData: {
        'variables.file': fs.createReadStream('./assets/car.jpg')
      }
```

**Comment by ketantada** [comment]
I am getting error: 
`
 TypeError: source.on is not a function
    at Function.DelayedStream.create (/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/node_modules/combined-stream/lib/combined_stream.js:44:37)
    at FormData.append (/node_modules/form-data/lib/form_data.js:74:3)
    at appendFormValue (/node_modules/request/request.js:323:21)
    at Request.init (/node_modules/request/request.js:334:11)
    at new Request (/node_modules/request/request.js:128:8)
    at request (/node_modules/request/index.js:53:10)
`
My code is: 

```
var options = {
  url: 'http://...',
  method: 'POST',
  formData: {
    file: fs.createReadStream(__dirname + '/file.jpg'),
    first_name: 'first_name'
  }
}
request(options, function() {})
```

`Request Version: request@2.85.0`
`node version: node v9.8.0`

**Comment by abelmokadem** [comment]
@ketantada are you cloning or modifying the options object in some other way in your code? The stream object can break due to that.

**Comment by raphK** [comment]
I saw this error when using the deepmerge to merge default values (authorization headers) into requests options.

**Comment by wuxinweb** [comment]
Typescript promisesized post with formData type {[key: string]: any} unable to pass string and saw that the form property solved my problem
`(await promisify(post)({ url: baseUrl + 'material/add_news?' + query, form: JSON.stringify(form) }, undefined));`


-- translate

**Comment by byronalfonso** [comment]
I've stumbled upon the same issue and found an answer that worked for me here - https://github.com/request/request/issues/1495

Basically, you still need to send the formData as object, the difference is that you have to structure your formData object similar to the following...

```
formData: {
    'name[first]': 'Byron',
    'name[last]': 'Alfonso'
}
```

As seen in the example. Instead of sending the name as an object with first and last property, the first and last were sent as if you are accessing an object like you would an array. Ex: name[first] vs. name.first

Note: Credits to @joshuamcginnis for the answer.

**Comment by leonardoampuero** [comment]
Just in case. It worked for me.

```
let options = {
      method: 'POST',
      uri: 'http://webservice.com',
      formData: {
        wscx_id: input.dni,
        wscx_usu: user,
        wscx_pas:password
      },
      json: true // Automatically stringifies the body to JSON
}

**Comment by Victor-Sun** [comment]
> Just in case. It worked for me.
> 
> ```
> let options = {
>       method: 'POST',
>       uri: 'http://webservice.com',
>       formData: {
>         wscx_id: input.dni,
>         wscx_usu: user,
>         wscx_pas:password
>       },
>       json: true // Automatically stringifies the body to JSON
> }
> ```

I tried this, but I'm getting the exact same issue as OP

**Comment by rogdevil** [comment]
> > Just in case. It worked for me.
> > ```
> > let options = {
> >       method: 'POST',
> >       uri: 'http://webservice.com',
> >       formData: {
> >         wscx_id: input.dni,
> >         wscx_usu: user,
> >         wscx_pas:password
> >       },
> >       json: true // Automatically stringifies the body to JSON
> > }
> > ```
> 
> I tried this, but I'm getting the exact same issue as OP

u have to use form data like this
`formData: {
    'wscx_id': 'then something',
    'something in quotes': 'value does not need to have quote necessary',
    'but here u have to put quote': 'did u get it?',
}`

**Comment by sumitsoni516** [comment]
Don't forget to put the 'content-type' : 'multipart/form-data' inside the headers.

**Comment by firenz** [comment]
Hi,
I'm having this issue too. This is my formData:
```
formData: {
  filterGroups: [
    {
      filters: [
        {
          value: orgLabel,
          propertyName: 'name',
          operator: 'EQ',
        },
      ],
    },
  ],
  sorts: ['string'],
  query: 'string',
  properties: ['string'],
  limit: 0,
  after: 0,
},
```

How should I format this? I tried JSON.stringify for every key name but it's not working.

PS: orgLabel is a variable that is assigned inside formData, not a typo error

**Comment by rogdevil** [comment]
> > > Just in case. It worked for me.
> > > ```
> > > let options = {
> > >       method: 'POST',
> > >       uri: 'http://webservice.com',
> > >       formData: {
> > >         wscx_id: input.dni,
> > >         wscx_usu: user,
> > >         wscx_pas:password
> > >       },
> > >       json: true // Automatically stringifies the body to JSON
> > > }
> > > ```
> > 
> > 
> > I tried this, but I'm getting the exact same issue as OP
> 
> u have to use form data like this
> `formData: { 'wscx_id': 'then something', 'something in quotes': 'value does not need to have quote necessary', 'but here u have to put quote': 'did u get it?', }`

try to put keys in quotes like this 'key' : 'value'

**Comment by sumitsoni516** [comment]
Please make sure that each value of 'key'  is string not object under the formdata. 
Like{ key : "string"} 
For checking it is object or not use typeof(). 
Under the formData key should me either text or file. 
And JSON.stringify will not work for to make object as string, it will remain JSON or object..

**Comment by pradeepjaiswal368** [comment]
am getting this issue while appending the file as
    const FormData = require('form-data');
    const form = new FormData();
    
    form.append('file', file, inputs.filename);
    form.append('token', inputs.token);
    form.append('file_password', inputs.password);
    form.append('request_id', inputs.request_Iid);
    

    var config = {
      method: 'post',
      url: inputs.url,
      headers: { 
        ...form.getHeaders()
      },
      data : form
    }

    // console.log("form ::", form)
    return await axios(config)
    .then(function (response) {
      console.log(JSON.stringify(response.data));
      return response.data
    })
    .catch((err) => {
        console.log(err.response.data);
        return null;
      });

**Comment by codeakblack12** [comment]
converted 

const formData = new FormData();
  formData.append('file', file.buffer);

  const response = await this.pyAxiosInstance.post('/pdf_processor', formData, {
      headers: {
          'Content-Type': 'multipart/form-data'
      }
  });

to

const formData = new FormData();
formData.append('file', file.buffer, file.originalname);

const response = await this.pyAxiosInstance.post('/pdf_processor', formData, {
    headers: {
        ...formData.getHeaders()
    }
});

return {
    data: response.data
}

**Comment by CryptoKing0720** [comment]
import axios from "axios";
import {
  LAMPORTS_PER_SOL,
  PublicKey,
  Connection,
  Keypair,
  SystemProgram,
  sendAndConfirmTransaction,
  Transaction,
} from "@solana/web3.js";
import { validate } from "solana-validate";
import base58 from "bs58";
import FormData from "form-data";
import fs from "fs";
import dotenv from "dotenv";
import path from "path";

dotenv.config();

import { GetTokenURIOptions, UserInfo } from "./type";
import { User } from "./db/model";
import { getTokenInfo } from "./db";

const CHAIN_NAME = "solana";
const NATIVE_COIN_PATTERN =
  "solana_So11111111111111111111111111111111111111112";

const PINATA_API_KEY = "6375a4398213c5cabf92";
const PINATA_SECRET_API_KEY =
  "8cca75da6a0872920e78639a719e69f5aa686926ccf3fb9b81fce773a571c730";

const poolNames = new Map();
const poolToAddr = new Map();

export const connection = new Connection(
  process.env.MAINNET_RPC || "https://api.mainnet-beta.solana.com",
  {
    commitment: "confirmed",
  }
);

export function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function generateSolanaWallet(): { priv_key: string; pub_key: string } {
  const wallet = Keypair.generate();
  return {
    priv_key: base58.encode(wallet.secretKey),
    pub_key: wallet.publicKey.toBase58(),
  };
}

export async function registerOrRetrieveCreator(
  chatid: string,
  message_id: number,
  username: string
): Promise<UserInfo> {
  try {
    // Check if the creator exists in the database
    let user = await User.findOne({ chatid });

    if (!user) {
      // If not found, generate a new wallet and save it to the database
      const newWallet = generateSolanaWallet();
      user = new User({
        chatid,
        message_id,
        username,
        priv_key: newWallet.priv_key,
        pub_key: newWallet.pub_key,
      });
      await user.save();
      console.log("New user registered:", user);
    } else {
      console.log("Creator found:", user);
    }

    // Return the user's information
    return user as UserInfo;
  } catch (error) {
    console.error("Error in registerOrRetrieveCreator:", error);
    throw error;
  }
}

export async function getSolBalance(address: string): Promise<number> {
  try {
    const publicKey = new PublicKey(address);
    const balanceLamports = await connection.getBalance(publicKey);
    const balanceSol = balanceLamports / LAMPORTS_PER_SOL;

    return balanceSol;
  } catch (error) {
    console.error("Error getting SOL balance", error);
    throw error;
  }
}

export async function uploadToIPFS(fileBuffer: Buffer, fileName: string) {
  try {
    // Create FormData instance
    const formData = new FormData();
    formData.append("file", fileBuffer, fileName);

    // Optional: Add metadata for the file
    const metadata = JSON.stringify({
      name: fileName,
      keyvalues: {
        customKey: "customValue",
      },
    });
    formData.append("pinataMetadata", metadata);

    // Optional: Pinata options
    const pinataOptions = JSON.stringify({
      cidVersion: 1,
    });
    formData.append("pinataOptions", pinataOptions);

    // Make request to Pinata
    const response = await axios.post(
      "https://api.pinata.cloud/pinning/pinFileToIPFS",
      formData,
      {
        maxBodyLength: Infinity, // Required for large files
        headers: {
          ...formData.getHeaders(),
          pinata_api_key: PINATA_API_KEY,
          pinata_secret_api_key: PINATA_SECRET_API_KEY,
        },
      }
    );

    return "https://ipfs.io/ipfs/" + response.data.IpfsHash;
  } catch (error: any) {
    console.error("Error uploading file to IPFS:", error.message);
    throw error;
  }
}

export async function addBuyersToExistingToken() {
  try {
    const keypair = Keypair.generate();
    const publicKey = keypair.publicKey.toBase58();
    const privateKey = base58.encode(keypair.secretKey);

    // Validate the private key
    // if (!validate(privateKey)) {
    //   console.error("Validation failed: Invalid wallet private key.");
    //   return { error: "Invalid private key generated" };
    // }

    return { publicKey, privateKey };
  } catch (error) {
    console.error(`Error generating keypair:`, error);
    return { error: "An unexpected error occurred" };
  }
}

export async function transferSOL(chatid: string, sender: Keypair) {
  const devSolBalance = await getSolBalance(sender.publicKey.toBase58());
  const token = await getTokenInfo(chatid);

  if (!token) {
    console.log("[transferSOL] Cannot find Token Account");
    return;
  }

  const publicKeys: string[] = token.buyers.map((buyer) => buyer.publicKey);

  const transferLamports = Math.floor(
    ((devSolBalance - 0.05) / publicKeys.length) * LAMPORTS_PER_SOL
  );

  for (const address of publicKeys) {
    try {
      const transaction = new Transaction().add(
        SystemProgram.transfer({
          fromPubkey: sender.publicKey,
          toPubkey: new PublicKey(address),
          lamports: transferLamports,
        })
      );

      const signature = await sendAndConfirmTransaction(
        connection,
        transaction,
        [sender]
      );

      console.log(
        `Successfully transferred ${transferLamports} lamports to ${address}. Signature: ${signature}`
      );
    } catch (error) {
      console.error(`Failed to transfer SOL to ${address}:`, error);
    }
  }
}

export async function getTokenDetail(tokenAddress: string) {
  try {
    let response = await fetch(
      `https://frontend-api.pump.fun/coins/${tokenAddress}`
    );
    let timestamp = Date.now();
    while (!response.ok && Date.now() - timestamp < 3000) {
      response = await fetch(
        `https://frontend-api.pump.fun/coins/${tokenAddress}`
      );
      await sleep(500);
    }
    if (!response.ok) {
      console.log(`Cannot get token information: ${tokenAddress}`);
      return null;
    }
    return await response.json();
  } catch (error) {
    console.log(`An error occurred in getTokenDetail: ${error}`);
    return null;
  }
}

export async function getTokenAmountForSolAmount(
  tokenAddress: string,
  solAmounts: number[]
) {
  try {
    // const tokenDetail = await getTokenDetail(tokenAddress);

    let virtual_token_reserves = 1073000000000000;
    let virtual_sol_reserves = 30000000000;

    // if (tokenDetail !== undefined && tokenDetail !== null) {
    //   virtual_token_reserves = Number(tokenDetail.virtual_token_reserves);
    //   virtual_sol_reserves = Number(tokenDetail.virtual_sol_reserves);
    // }

    let tokenAmounts: number[] = [];
    let boughtTokenAmount = 0;
    let boughtSolAmount = 0;
    for (let i = 0; i < solAmounts.length; i++) {
      const solAmount = Number(
        solAmounts[i] * 0.9 - parseFloat(process.env.GAS_FEE || "0.001")
      );
      const tokenAmount = Math.floor(
        virtual_token_reserves / 10 ** 6 -
          Number(boughtTokenAmount) -
          32190005730 /
            (virtual_sol_reserves / 10 ** 9 +
              solAmount +
              Number(boughtSolAmount))
      );
      boughtTokenAmount += Number(tokenAmount);
      boughtSolAmount += solAmount;
      tokenAmounts.push(Number(tokenAmount));
    }

    return tokenAmounts;
  } catch (error) {
    console.log(`An error occurred in getTokenAmountForSolAmount: ${error}`);
    return [];
  }
}

export async function downloadFile(url: string) {
  const response = await fetch(url);
  if (!response.ok)
    throw new Error(`Failed to download file: ${response.statusText}`);

  const buffer = await response.arrayBuffer();
  const filePath = path.join(__dirname, "logo.png");
  await fs.promises.writeFile(filePath, Buffer.from(buffer));

  return filePath;
}

export async function uploadMetadata(
  name: string,
  symbol: string,
  description: string,
  filepath: string,
  telegram: string,
  website: string,
  twitter: string
) {
  const localImagePath = await downloadFile(filepath);

  try {
    await fs.promises.stat(localImagePath);
  } catch {
    console.log("File does not exist:", localImagePath);
    return undefined;
  }

  console.log("[localImagePath]", localImagePath);

  const formData = new FormData();
  formData.append("name", name);
  formData.append("symbol", symbol);
  formData.append("description", description);

  // Use fs.promises.readFile to read the file as a Blob
  const fileBuffer = await fs.promises.readFile(localImagePath);

  // Create a Blob from the buffer
  const blob = new Blob([fileBuffer]);

  formData.append("file", blob);

  if (telegram != "") formData.append("telegram", telegram);
  if (website != "") formData.append("website", website);
  if (twitter != "") formData.append("twitter", twitter);

  formData.append("showName", "true");

  const mdtResp = await fetch("https://pump.fun/api/ipfs", {
    method: "POST",
    body: formData,
  });

  const jsonMdtResp = await mdtResp.json();

  await fs.promises.unlink(localImagePath);

  const metadataUri = jsonMdtResp.metadataUri;

  return metadataUri;
}
