### ISSUE TITLE
Error: Cannot convert name to ASCII

### ISSUE THREAD

**Issue by Laptinius** [request/request#2422]
```
var request = require("request");
request('http://remont-stiralnikh-mashin-krasnoyarsk.ru/', function(error, response, body){
  console.log('LOAD', error);
});
```

```
url.js:320
      this.hostname = toASCII(this.hostname);
                      ^

Error: Cannot convert name to ASCII
    at Error (native)
    at Url.parse (url.js:320:23)
    at Object.urlParse [as parse] (url.js:81:5)
    at Redirect.onResponse (D:\work\projects\nodejs\v1\node_modules\request\lib\redirect.js:104:21)
    at Request.onRequestResponse (D:\work\projects\nodejs\v1\node_modules\request\request.js:885:22)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:472:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:361:20)
```

nodejs: v6.7.0
request: 3.10.3

**Comment by marvinhagemeister** [comment]
I'm hit by the same issue on node `7.10.0`. I'm unsure how to debug further since this seems to call into native code :/

**Comment by cuttlfish** [comment]
I ran into this problem on node 8.X. It was caused by ICU version 65. Disabling ICU in node or downgrading version to 57 both fixed the problem
