### ISSUE TITLE
Error with proxy

### ISSUE THREAD

**Issue by Deadly0** [request/request#2423]
Everything works well on dev machine (windows) but when i deploying the app to the server (Ubuntu) strange error happened.
When i set http proxy to request it throws the error for every request
```
AssertionError: 20 == 0
  at ClientRequest.onConnect (/home/carmod/www/avitoparser/bundle/programs/server/npm/node_modules/tunnel-agent/index.js:159:14)
  at ClientRequest.g (events.js:260:16)
  at emitThree (events.js:97:13)
  at ClientRequest.emit (events.js:175:7)
  at Socket.socketOnData (_http_client.js:354:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at Socket.Readable.push (_stream_readable.js:111:10)
  at TCP.onread (net.js:536:20)
```

No ideas how to catch the error and why it happened.

**Comment by Laptinius** [comment]
+

**Comment by pepzwee** [comment]
It has something to do with trying to open ``https://example.com`` when you have a ``http`` proxy. When I changed it to ``http://example.com`` no more errors were thrown.
