### ISSUE TITLE
Crashes when two pages are opened simultanously

### ISSUE THREAD

**Issue by adek05** [request/request#2429]
Are there any known race conditions in phantom? How can I start debugging this?
```
undefined:1
{"id":"deb4d64af00cf5ca0eb97df932400058","target":"page$7a9dbd6a71bb45a6b62c7fce079308b1","name":"invokeMethod","params":["evaluate",null],"response":{"0":{"ALLOW_KEYBOARD_INPUT":1,"ATTRIBUTE_NODE":2,"CDATA_SECTION_NODE":4,"COMMENT_NODE":8,"DOCUMENT_FRAGMENT_NODE":11,"DOCUMENT_NODE":9,"DOCUMENT_POSITION_CONTAINED_BY":16,"DOCUMENT_POSITION_CONTAINS":8,"DOCUMENT_POSITION_DISCONNECTED":1,"DOCUMENT_POSITION_FOLLOWING":4,"DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC":32,"DOCUMENT_POSITION_PRECEDING":2,"DOCUMENT_TYPE_NODE":10,"ELEMENT_NODE":1,"ENTITY_NODE":6,"ENTITY_REFERENCE_NODE":5,"NOTATION_NODE":12,"PROCESSING_INSTRUCTION_NODE":7,"TEXT_NODE":3,"accessKey":"","addEventListener":null,"align":"","appendChild":null,"attributes":{"0":{"ATTRIBUTE_NODE":2,"CDATA_SECTION_NODE":4,"COMMENT_NODE":8,"DOCUMENT_FRAGMENT_NODE":11,"DOCUMENT_NODE":9,"DOCUMENT_POSITION_CONTAINED_BY":16,"DOCUMENT_POSITION_CONTAINS":8,"DOCUMENT_POSITION_DISCONNECTED":1,"DOCUMENT_POSITION_FOLLOWING":4,"DOCUMENT_POSITION_IMPLEMENTATION_SP

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Liner.<anonymous> (/usr/src/app/node_modules/phantom/lib/phantom.js:144:36)
    at emitOne (events.js:96:13)
    at Liner.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Liner.Readable.push (_stream_readable.js:135:10)
    at Liner.Transform.push (_stream_transform.js:128:32)
    at Liner.flush [as _flush] (/usr/src/app/node_modules/linerstream/index.js:26:10)
    at Liner.<anonymous> (_stream_transform.js:118:12)
    at Liner.g (events.js:286:16)

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start-server"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

**Comment by mscdex** [comment]
It looks like it should've be left on the [`phantom` issue tracker](https://github.com/amir20/phantomjs-node/issues) instead? This issue tracker is for the `request` module.

**Comment by adek05** [comment]
I thought this is more related to the Phantom itself, but if you say so, I'll move it there.
