### ISSUE TITLE
on('error') fired twice on timeout of keep-alive socket

### ISSUE THREAD

**Issue by bsyk** [request/request#2485]
When setting a timeout on a request as in this code:
```js
const express = require('express');
const request = require('request');
require('request-debug')(request);
require('simple-errors');

const app = express();

// The code for /slow/ping just sleeps for 30s before responding.  It's just this:
// app.use('/slow/ping', (req, res) => setTimeout(() => res.send('delayed pong'), 30000));
app.use('/test/*', (req, res, next) => {
  const apiRequest = request({
    url: 'http://localhost:9000/slow/ping',
    timeout: 2000
  });

  apiRequest.on('error', (err) => {
    console.log('unhandled API error:', err.code);
    if (err.code === 'ETIMEDOUT' || err.code === 'ESOCKETTIMEDOUT') {
      return next(Error.http(408, 'API call timed out'));
    }
    return next(err);
  });

  // Defer piping the response until the response event so we can
  // check the status code.
  apiRequest.on('response', (resp) => {
    // Do not attempt to apply transforms to error responses
    if (resp.statusCode >= 400) {
      console.log(`Received error ${resp.statusCode} from ${apiRequestOptions.url}`);
      return apiRequest.pipe(res);
    }

    return apiRequest.pipe(res);
  });
});

app.listen(12345);
```

If the timeout occurs the ``ETIMEDOUT`` is correctly emitted.  However, on subsequent requests to the same endpoint, it appears that the original socket is re-used and then 2 errors are emitted.  Both ``ETIMEDOUT `` and ``ESOCKETTIMEDOUT``.

This is usually on the second or third refresh.

In an expressjs application, this causes the error handler to fire twice, which breaks the application.
This sample app is a much-reduced use of request based on [express-request-proxy](https://github.com/4front/express-request-proxy)

Here's a trace from sample app above:
```shell
BSYK:ui-shell BSYK$ DEBUG=* node test.js 
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +3ms
  express:application set "etag fn" to [Function: wetag] +2ms
  express:application set "env" to 'development' +0ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +1ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/Users/BSYK/Documents/workspace-scratch/ui-shell/views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:router use / query +1ms
  express:router:layer new / +0ms
  express:router use / expressInit +1ms
  express:router:layer new / +0ms
  express:router use /test/* <anonymous> +0ms
  express:router:layer new /test/* +1ms
  express:router dispatching GET /test/slow/ping +2s
  express:router query  : /test/slow/ping +1ms
  express:router expressInit  : /test/slow/ping +1ms
  express:router trim prefix (/test/slow/ping) from url /test/slow/ping +1ms
  express:router <anonymous> /test/slow/ping : /test/slow/ping +0ms
{ request: 
   { debugId: 1,
     uri: 'http://localhost:9000/slow/ping',
     method: 'GET',
     headers: { host: 'localhost:9000' } } }
unhandled API error: ETIMEDOUT
  finalhandler default 408 +2s
Error: API call timed out
    at Function.Error.create (/Users/BSYK/Documents/workspace-scratch/ui-shell/node_modules/simple-errors/index.js:25:11)
    at Function.Error.http (/Users/BSYK/Documents/workspace-scratch/ui-shell/node_modules/simple-errors/index.js:68:21)
    at Request.apiRequest.on (/Users/BSYK/Documents/workspace-scratch/ui-shell/test.js:19:25)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Timeout._onTimeout (/Users/BSYK/Documents/workspace-scratch/ui-shell/node_modules/request/request.js:775:12)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
  express:router dispatching GET /test/slow/ping +2s
  express:router query  : /test/slow/ping +1ms
  express:router expressInit  : /test/slow/ping +0ms
  express:router trim prefix (/test/slow/ping) from url /test/slow/ping +0ms
  express:router <anonymous> /test/slow/ping : /test/slow/ping +0ms
{ request: 
   { debugId: 2,
     uri: 'http://localhost:9000/slow/ping',
     method: 'GET',
     headers: { host: 'localhost:9000' } } }
unhandled API error: ESOCKETTIMEDOUT
unhandled API error: ETIMEDOUT
  finalhandler default 408 +2s
  finalhandler default 408 +0ms
_http_outgoing.js:356
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at Array.write (/Users/BSYK/Documents/workspace-scratch/ui-shell/node_modules/express/node_modules/finalhandler/index.js:164:9)
    at listener (/Users/BSYK/Documents/workspace-scratch/ui-shell/node_modules/on-finished/index.js:169:15)
    at onFinish (/Users/BSYK/Documents/workspace-scratch/ui-shell/node_modules/on-finished/index.js:100:5)
    at callback (/Users/BSYK/Documents/workspace-scratch/ui-shell/node_modules/ee-first/index.js:55:10)
    at IncomingMessage.onevent (/Users/BSYK/Documents/workspace-scratch/ui-shell/node_modules/ee-first/index.js:93:5)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

Tested only on mac with node v6.9.1 and v7.2.1

**Comment by bsyk** [comment]
Interestingly, or not, I can only reproduce this using a localhost URL.  If the request is going out to a real network, then the ``ESOCKETTIMEDOUT `` is never emitted.

**Comment by bsyk** [comment]
I think this is a race condition.  If I adjust the timeout code for the ``ESOCKETTIMEDOUT`` to be delayed by 1ms, the double error is not emitted on localhost, which then behaves as a remote URL does.

Change this line https://github.com/request/request/blob/v2.72.0/request.js#L786
```js
self.req.setTimeout(timeout+1, function () {
```

**Comment by bsyk** [comment]
Thanks for responding @mikeal.  While doing more debugging, I've found that this issue existed in v2.72.0 that I was using, but I am unable to reproduce this issue with the latest v2.79.1.
I propose closing this now.

**Comment by mikeal** [comment]
great to heard :)
