### ISSUE TITLE
cannot set property '_aborted' of undefined in Request.prototype.abort

### ISSUE THREAD

**Issue by yawhide** [request/request#2522]
I put a console.log(this) and a console.trace at request.js:1086. I am on the latest npm request version of this lib. 2.79.0 i think.
I am trying to call req.abort when downloading a file from a server.
```
console.log at line request.js:1086 -> "self in Request.prototype.abort: undefined"
consol.trace at line request.js:1086 -> Trace
    at Request.abort (/home/ops/diamond-integrations/node_modules/request/request.js:1088:11)
    at null._onTimeout (/home/ops/dexter/worker.js:65:5)
    at Timer.listOnTimeout (timers.js:92:15)

// the error below is thrown
TypeError: Cannot set property '_aborted' of undefined
    at Request.abort (/home/ops/diamond-integrations/node_modules/request/request.js:1089:17)
    at null._onTimeout (/home/ops/dexter/worker.js:65:5)
    at Timer.listOnTimeout (timers.js:92:15)
```

code that is causing this (not all the time which is weird :/)
```
var req = request({ method: 'POST', url: 'dropbox something', headers: {...}});
req.on('response', (res) => { check status code >= 400, if it is, do a res.on('data') to get the body and print the error } );
req.pipe(nodejs writeStream);
```
then I have a setTimeout with a `req.abort()` inside later on and I get the error above.
I realize i could just add a timeout in the original request. but this should be ok to do as well?

Any insight would be great. thanks

**Comment by yawhide** [comment]
i was doing dumb stuff with closures. sorry
