### ISSUE TITLE
how catch ETIMEDOUT error

### ISSUE THREAD

**Issue by hktalent** [request/request#2631]
Error: ETIMEDOUT
    at Timeout._onTimeout (/usr/local/lib/node_modules/crawler/node_modules/request/request.js:813:19)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) code: 'ETIMEDOUT', connect: true

**Comment by iamfreee** [comment]
Also need to know this

**Comment by jacktuck** [comment]
Just listen for error
Like this:
https://github.com/jacktuck/unfurl/commit/dab70fceee98d09c71bcda40c775610e0de58996

**Comment by iamfreee** [comment]
I was making a lot of requests to a down website at the moment.

I am trying this:
http://stackoverflow.com/a/37946399/2741122

Thanks for your reply also.
