### ISSUE TITLE
Error is thrown even when a handler/listener was set

### ISSUE THREAD

**Issue by gvuyk** [request/request#2643]
### Summary

When making a request to a site with https through a proxy, under some circumstances an error is thrown even when an error handler was set

### Simplest Example to Reproduce

```js
var request = require("request");
var concurrency = 1;
var requestOptions = {
	uri: "https://google.com",
	proxy: {
		hostname: "138.68.129.67",
		port: 8118,
		protocol: "http:"
	}
};

for(var i=0; i<concurrency; i++)
{
	request.get(requestOptions, function(error, response, body)
	{
		if(error){console.log(error);}
		if(body){console.log(body);}
	});
}
```
Definitely not the best way to reproduce it, I know. Will update when I get the time to write a failing proxy

### Expected Behavior

If an error occurs, it should be printed without crashing the app

### Current Behavior

The app crashes with the following error:
```
{ Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (D:\projects\test\node_modules\request\node_modules\tunnel-agent\index.js:166:19)
    at Object.onceWrapper (events.js:293:19)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:197:7)
    at Socket.socketOnData (_http_client.js:443:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20) code: 'ECONNRESET' }
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:581:26)
```

### Context

If this is a bug, seems like its related to the proxy closing the connection when its overloaded. The particular proxy in the example above is overloaded most of the time, it does not produce the error when its not, thats why the `concurrency` var is there for heheh . If you can't reproduce the problem with 1 request, I've been successfully reproducing it with 100

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.81.0
| node             | 7.9.0
| npm              | 4.2.0
| Operating System | Windows 10 and Ubuntu 16.04

**Comment by xinshangshangxin** [comment]
I found if i request with `http`, it will work correct, if request with `https`, it will show `tunneling socket could not be established`

**Comment by roy7** [comment]
You might be seeing the same problem as this: https://github.com/request/request/issues/2161. 

I have a script running with nodemon that, now and then, won't restart when I change the file. It continues to run normally, nodemon just doesn't restart it. If I control-C the process, it throws an unhanded error event and mentions ECONNRESET. No idea how to catch that in my code, unless it's an internal issue/error in nodemon itself.
