### ISSUE TITLE
Error: Cannot find module 'mime-types'

### ISSUE THREAD

**Issue by jadekler** [request/request#2723]
Request `2.81.0`:

```
2017-07-24T19:28:43.498Z	dcb51919-70a5-11e7-93c7-cff323e34537	Error: Cannot find module 'mime-types'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/node_modules/request/request.js:13:12)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
```

**Comment by jadekler** [comment]
Turned out to be a `serverless` issue!

**Comment by lucasklaassen** [comment]
@jadekler what ended up being the `serverless` issue?
