### ISSUE TITLE
can't setCookie

### ISSUE THREAD

**Issue by odilitime** [request/request#2747]
### Summary
Can't interact with cookie jar as described in documentation

### Simplest Example to Reproduce
```js
    var cookieText='laravel_session=1'
    var j = request.jar()
    var cookie = request.cookie(cookieText)
    j.setCookie(cookie, 'https://bob.alice/')
```

### Expected Behavior
no errors

### Current Behavior
```
/root/app.js:70
    j.setCookie(cookie, 'https://bob.alice/')
      ^

TypeError: j.setCookie is not a function
    at Object.module.exports.getFeed (/root/gab.js:70:7)
    at Object.mastodon.onTimelineHome (/root/gabstadon.js:98:7)
    at Server.handler (/root/mastodon.js:319:26)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:528:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)

```

### Possible Solution
Update documentation?

### Context
Can't set my cookie in a fresh jar

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.81.0
| node             | 4.2.5
| npm              | 3.5.2
| Operating System | Ubuntu linux (xenial 16.04LTS)

**Comment by odilitime** [comment]
Just used: headers.cookie: 'key=value'
