### ISSUE TITLE
Request module (hoek module) - SyntaxError: Unexpected token >

### ISSUE THREAD

**Issue by dmitriiPopov** [request/request#2805]
I have node version - 8.8.1
Request end hoek versions - 5.5.1

1) I launch: `node --harmony /var/www/vhosts/test/bot.js`
2) And get error:
`
/var/www/vhosts/test/node_modules/hoek/lib/index.js:371
exports.unique = (array, key) => {
                               ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/vhosts/test/node_modules/boom/lib/index.js:5:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
`

Without `--harmony` I get error:
`const express = require('express')
^^^^^
SyntaxError: Use of const in strict mode.`

I've reinstalled npm and modules, but it didn't help.

**Comment by oscarsiniscalchi** [comment]
I am getting the same issue.

**Comment by ximet** [comment]
the same error

**Comment by flundstrom2** [comment]
Same with me. Since I don't shit about JS, I've just installed nodejs, and tried to execute a js-file I've received, by installing the npm modules it required along the way:
```
debian@debian: ~/Import $ rm -rf node_modules
debian@debian: ~/Import $ nodejs index.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'fast-csv'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/debian/Import/index.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
debian@debian: ~/Import $ npm install fast-csv
npm WARN package.json panda-csv@1.0.0 No repository field.
npm WARN package.json panda-csv@1.0.0 No README data
npm WARN engine fast-csv@2.4.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
fast-csv@2.4.0 node_modules/fast-csv
├── is-extended@0.0.10
├── object-extended@0.0.7 (array-extended@0.0.11)
├── extended@0.0.6 (extender@0.0.10)
└── string-extended@0.0.8 (date-extended@0.0.6, array-extended@0.0.11)
debian@debian: ~/Import $ nodejs index.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'request-promise-native'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/debian/Import/index.js:5:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
debian@debian: ~/Import $ npm install request-promise-native
npm WARN package.json panda-csv@1.0.0 No repository field.
npm WARN package.json panda-csv@1.0.0 No README data
npm WARN engine request-promise-native@1.0.4: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine request@2.83.0: wanted: {"node":">= 4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine har-validator@5.0.3: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine form-data@2.3.1: wanted: {"node":">= 0.12"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine har-schema@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@4.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@4.3.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine sntp@2.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@3.1.2: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@5.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine request@2.83.0: wanted: {"node":">= 4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine form-data@2.3.1: wanted: {"node":">= 0.12"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine har-validator@5.0.3: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine har-schema@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@4.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@4.3.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@3.1.2: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine sntp@2.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@5.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
request@2.83.0 node_modules/request
├── is-typedarray@1.0.0
├── aws-sign2@0.7.0
├── oauth-sign@0.8.2
├── forever-agent@0.6.1
├── tunnel-agent@0.6.0
├── caseless@0.12.0
├── stringstream@0.0.5
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── safe-buffer@5.1.1
├── extend@3.0.1
├── aws4@1.6.0
├── performance-now@2.1.0
├── uuid@3.1.0
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── qs@6.5.1
├── form-data@2.3.1 (asynckit@0.4.0)
├── mime-types@2.1.17 (mime-db@1.30.0)
├── hawk@6.0.2 (sntp@2.1.0, boom@4.3.1, hoek@4.2.0, cryptiles@3.1.2)
├── tough-cookie@2.3.3 (punycode@1.4.1)
├── http-signature@1.2.0 (assert-plus@1.0.0, jsprim@1.4.1, sshpk@1.13.1)
└── har-validator@5.0.3 (har-schema@2.0.0, ajv@5.5.2)

request-promise-native@1.0.4 node_modules/request-promise-native
├── stealthy-require@1.1.1
├── tough-cookie@2.3.3 (punycode@1.4.1)
├── request@2.83.0 (is-typedarray@1.0.0, aws-sign2@0.7.0, oauth-sign@0.8.2, forever-agent@0.6.1, tunnel-agent@0.6.0, caseless@0.12.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, safe-buffer@5.1.1, extend@3.0.1, aws4@1.6.0, performance-now@2.1.0, uuid@3.1.0, qs@6.5.1, combined-stream@1.0.5, form-data@2.3.1, hawk@6.0.2, mime-types@2.1.17, http-signature@1.2.0, har-validator@5.0.3)
└── request-promise-core@1.1.1 (lodash@4.17.4)
debian@debian: ~/Import $ nodejs index.js 

/home/debian/Import/node_modules/request-promise-native/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/debian/Import/node_modules/request-promise-native/node_modules/request/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
debian@debian: ~/Import $ npm install hoek
npm WARN package.json panda-csv@1.0.0 No repository field.
npm WARN package.json panda-csv@1.0.0 No README data
npm WARN engine hoek@5.0.2: wanted: {"node":">=8.9.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
hoek@5.0.2 node_modules/hoek
debian@debian: ~/Import $ nodejs index.js 

/home/debian/Import/node_modules/request-promise-native/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/debian/Import/node_modules/request-promise-native/node_modules/request/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
debian@debian: ~/Import $ 

```
