### ISSUE TITLE
socket hang up Error?? 

### ISSUE THREAD

**Issue by vishuPPatel** [request/request#2858]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

any body know abut why socket hang up error occur i requested to (http) post method throw??

Thanks!!.... in Advance...

**Comment by lettoka** [comment]
im facing the same problem, have you solved it?

**Comment by airbone42** [comment]
+1

**Comment by lettoka** [comment]
Don't use http.request. You should use other modules for sending request, I suggest the request module itself, it works fine for me.
 I hope I could help :)

**Comment by soomrox** [comment]
I have the same problem - Please help ....


events.js:136                                                                                                                                            
      throw er; // Unhandled 'error' event                                                                                                               
      ^                                                                                                                                                  
                                                                                                                                                         
Error: socket hang up
    at createHangUpError (_http_client.js:330:15)  
    at Socket.socketOnEnd (_http_client.js:423:23)  
    at Socket.emit (events.js:164:20)             
    at endReadableNT (_stream_readable.js:1054:12) 
    at _combinedTickCallback (internal/process/next_tick.js:138:11)  
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by vpanwar821** [comment]
I am using the request module but still getting the same problem, please help.

**Comment by soomrox** [comment]
Hi, just to update everyone. My issue got sorted. Upon troubleshooting this further I realized I need more Memory RAM. Once I increased the capacity I do not have the crash now

**Comment by puneetkhanduri** [comment]
+1. We are seeing the same issue.
