### ISSUE TITLE
https POST request hangs when executing from aws ec2 machine 

### ISSUE THREAD

**Issue by krebbl** [request/request#2868]
### Summary
Https POST request hangs when running it from an aws EC2 machine.
The request works well with cURL or when running the script from my local machine.
 
### Simplest Example to Reproduce

```js
const request = require('request');
request.debug = true;

request.post({
    url: 'https://www.spreadshirt.de/api/v1/shops/1133169/products' + '?mediaType=json&locale=de_DE&sig=c6603c470abfcd00bf07556135a5b14f25989aa5&time=1518110258642&apiKey=2b065dd3-88b7-44a8-87fe-e564ed27f904&mode=designer',
    body: JSON.parse('{"productType":{"id":"812"},"configurations":[{"designs":[{"id":"144135648","href":"/u144135648"}],"offset":{"x":91.452,"y":85.31},"printArea":{"id":"1667"},"printType":{"id":"17"},"content":{"unit":"mm","dpi":"25.4","svg":{"image":{"transform":"","width":125.151,"height":83.35,"designId":"144135648"}}},"restrictions":{"changeable":true},"properties":{"afterEffect":{"id":"646ee378-28af-48bd-b956-41f47ca9bf11","offset":{"x":20,"y":30},"scale":{"x":0.7200000000000001,"y":0.7200000000000001},"fixedAspectRatio":null,"originalDesign":{"id":"144135267","href":"/u144135267"}},"type":"afterEffect"},"type":"design"}],"appearance":{"id":"2"},"restrictions":{"example":false,"freeColorSelection":true},"defaultValues":{"defaultView":{"id":"1"}},"creator":"Sketchomat"}'),
    json: true,
    headers: {
        'Host': 'www.spreadshirt.de',
        'Cache-Control': 'no-cache',
        'Origin': 'https://www.spreadshirt.de',
        'Content-Type': 'application/json; charset=UTF-8',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36'
    },
    agentOptions: {
        rejectUnauthorized: false,
        keepAlive: true,                // workaround part i.
        secureProtocol: 'TLSv1_2_method', // workaround part ii.
        ciphers: 'ECDHE-RSA-AES256-GCM-SHA384',
        honorCipherOrder: true
    },
    gzip: true
}, function(e, r, body){
    console.log(e);
    console.log("request returned");
    console.log(body);
});
```

### Expected Behavior
Output when running it from my local machine:
```
REQUEST { url: 'https://www.spreadshirt.de/api/v1/shops/1133169/products?mediaType=json&locale=de_DE&sig=c6603c470abfcd00bf07556135a5b14f25989aa5&time=1518110258642&apiKey=2b065dd3-88b7-44a8-87fe-e564ed27f904&mode=designer',
  body: 
   { productType: { id: '812' },
     configurations: [ [Object] ],
     appearance: { id: '2' },
     restrictions: { example: false, freeColorSelection: true },
     defaultValues: { defaultView: [Object] },
     creator: 'Sketchomat' },
  json: true,
  headers: 
   { Host: 'www.spreadshirt.de',
     'Cache-Control': 'no-cache',
     Origin: 'https://www.spreadshirt.de',
     'Content-Type': 'application/json; charset=UTF-8',
     'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36' },
  agentOptions: 
   { rejectUnauthorized: false,
     keepAlive: true,
     secureProtocol: 'TLSv1_2_method',
     ciphers: 'ECDHE-RSA-AES256-GCM-SHA384',
     honorCipherOrder: true },
  gzip: true,
  callback: [Function],
  method: 'POST' }
REQUEST make request https://www.spreadshirt.de/api/v1/shops/1133169/products?mediaType=json&locale=de_DE&sig=c6603c470abfcd00bf07556135a5b14f25989aa5&time=1518110258642&apiKey=2b065dd3-88b7-44a8-87fe-e564ed27f904&mode=designer
REQUEST onRequestResponse https://www.spreadshirt.de/api/v1/shops/1133169/products?mediaType=json&locale=de_DE&sig=c6603c470abfcd00bf07556135a5b14f25989aa5&time=1518110258642&apiKey=2b065dd3-88b7-44a8-87fe-e564ed27f904&mode=designer 201 { 'x-application-context': 'application:2379',
  location: 'https://api.spreadshirt.net/api/v1/shops/1133169/products/179874875',
  'content-type': 'application/json',
  'content-length': '95',
  server: 'nginx/9.5',
  'cache-control': 'max-age=3582',
  date: 'Sun, 11 Feb 2018 13:55:06 GMT',
  connection: 'keep-alive',
  'set-cookie': 
   [ 'sprd_auth_token=;Version=1;Domain=.spreadshirt.net;Path=/;Max-Age=0;HttpOnly;Expires=Thu, 01 Jan 1970 00:00:00 GMT',
     'ak_bmsc=B376C314600A33262289642D0BEC923A170E5EC0117E00003A4B805AFAB6973F~pl7PWsiI1LXxBi12IipyMDA+ivQCFXelsA12thQHeDHlUbllkNNjTxC5Iui4/hCST8SCpNqsLTWV2dN4SOT0czmMR+ww15vULTEzou0CrYCuiuurqKSNW2tsMHYtVIdKQiaQEdM0t4rng7i350yAtyiXw490abaZM2wERXkt1Wra0c4Z2q72sfXcP1RGr2VBwQRfzSQvKMq+XBYEF0/dqRkAc/vLBEnVPZ5OORsxC4ojQ=; expires=Sun, 11 Feb 2018 15:55:06 GMT; max-age=7200; path=/; domain=.spreadshirt.de; HttpOnly' ],
  'x-prefetch': 'yes',
  'x-robots-tag': 'noindex, nofollow',
  'x-country': 'DE',
  'x-device': 'desktop',
  'x-application': 'website',
  'x-dns-prefetch-control': 'on' }
REQUEST reading response's body
REQUEST finish init function https://www.spreadshirt.de/api/v1/shops/1133169/products?mediaType=json&locale=de_DE&sig=c6603c470abfcd00bf07556135a5b14f25989aa5&time=1518110258642&apiKey=2b065dd3-88b7-44a8-87fe-e564ed27f904&mode=designer
REQUEST response end https://www.spreadshirt.de/api/v1/shops/1133169/products?mediaType=json&locale=de_DE&sig=c6603c470abfcd00bf07556135a5b14f25989aa5&time=1518110258642&apiKey=2b065dd3-88b7-44a8-87fe-e564ed27f904&mode=designer 201 { 'x-application-context': 'application:2379',
  location: 'https://api.spreadshirt.net/api/v1/shops/1133169/products/179874875',
  'content-type': 'application/json',
  'content-length': '95',
  server: 'nginx/9.5',
  'cache-control': 'max-age=3582',
  date: 'Sun, 11 Feb 2018 13:55:06 GMT',
  connection: 'keep-alive',
  'set-cookie': 
   [ 'sprd_auth_token=;Version=1;Domain=.spreadshirt.net;Path=/;Max-Age=0;HttpOnly;Expires=Thu, 01 Jan 1970 00:00:00 GMT',
     'ak_bmsc=B376C314600A33262289642D0BEC923A170E5EC0117E00003A4B805AFAB6973F~pl7PWsiI1LXxBi12IipyMDA+ivQCFXelsA12thQHeDHlUbllkNNjTxC5Iui4/hCST8SCpNqsLTWV2dN4SOT0czmMR+ww15vULTEzou0CrYCuiuurqKSNW2tsMHYtVIdKQiaQEdM0t4rng7i350yAtyiXw490abaZM2wERXkt1Wra0c4Z2q72sfXcP1RGr2VBwQRfzSQvKMq+XBYEF0/dqRkAc/vLBEnVPZ5OORsxC4ojQ=; expires=Sun, 11 Feb 2018 15:55:06 GMT; max-age=7200; path=/; domain=.spreadshirt.de; HttpOnly' ],
  'x-prefetch': 'yes',
  'x-robots-tag': 'noindex, nofollow',
  'x-country': 'DE',
  'x-device': 'desktop',
  'x-application': 'website',
  'x-dns-prefetch-control': 'on' }
REQUEST end event https://www.spreadshirt.de/api/v1/shops/1133169/products?mediaType=json&locale=de_DE&sig=c6603c470abfcd00bf07556135a5b14f25989aa5&time=1518110258642&apiKey=2b065dd3-88b7-44a8-87fe-e564ed27f904&mode=designer
REQUEST has body https://www.spreadshirt.de/api/v1/shops/1133169/products?mediaType=json&locale=de_DE&sig=c6603c470abfcd00bf07556135a5b14f25989aa5&time=1518110258642&apiKey=2b065dd3-88b7-44a8-87fe-e564ed27f904&mode=designer 95
REQUEST emitting complete https://www.spreadshirt.de/api/v1/shops/1133169/products?mediaType=json&locale=de_DE&sig=c6603c470abfcd00bf07556135a5b14f25989aa5&time=1518110258642&apiKey=2b065dd3-88b7-44a8-87fe-e564ed27f904&mode=designer
null
request returned
{ href: 'https://api.spreadshirt.net/api/v1/shops/1133169/products/179874875',
  id: '179874875' }
```

### Current Behavior
Output when I am running it from AWS:
```
REQUEST { url: 'https://www.spreadshirt.de/api/v1/shops/1133169/products?mediaType=json&locale=de_DE&sig=c6603c470abfcd00bf07556135a5b14f25989aa5&time=1518110258642&apiKey=2b065dd3-88b7-44a8-87fe-e564ed27f904&mode=designer',
  body:
   { productType: { id: '812' },
     configurations: [ [Object] ],
     appearance: { id: '2' },
     restrictions: { example: false, freeColorSelection: true },
     defaultValues: { defaultView: [Object] },
     creator: 'Sketchomat' },
  json: true,
  headers:
   { 'Content-Length': '765',
     Host: 'www.spreadshirt.de',
     Accept: '*/*',
     'Cache-Control': 'no-cache',
     Origin: 'https://www.spreadshirt.de',
     'Content-Type': 'application/json; charset=UTF-8',
     'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36' },
  gzip: true,
  agentOptions:
   { rejectUnauthorized: false,
     keepAlive: true,
     secureProtocol: 'TLSv1_2_method',
     ciphers: 'ECDHE-RSA-AES256-GCM-SHA384',
     honorCipherOrder: true },
  callback: [Function],
  method: 'POST' }
REQUEST make request https://www.spreadshirt.de/api/v1/shops/1133169/products?mediaType=json&locale=de_DE&sig=c6603c470abfcd00bf07556135a5b14f25989aa5&time=1518110258642&apiKey=2b065dd3-88b7-44a8-87fe-e564ed27f904&mode=designer
{ name: 'ECDHE-RSA-AES256-GCM-SHA384', version: 'TLSv1/SSLv3' }
```
It fails after some seconds with this error
```
{ Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
``` 

### Possible Solution
It would be helpful to get more output on what is actually happening under the hood.
I don't get why the post works with CURL but not with the script.  

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.83.0
| node             | 9.5.0
| npm              | 5.6.0
| Operating System |  Linux

**Comment by krebbl** [comment]
found out that the root cause is a sophisticated bot blocker in the spreadshirt api. so closing this
