### ISSUE TITLE
Proxy a POST request with multipart/form-data body ERROR: First argument must be a string or Buffer stack

### ISSUE THREAD

**Issue by loretoparisi** [request/request#2892]
I have to proxy a POST request that has a multi-part body image
```javascript
app.post(self._options.baseUrl + '/image.post', function (req, res) {
                delete req.headers.host;
                request.post('http://localhost:9080/image.post', { headers: req.headers, body: req.body }, function (error, response, body) {
                    if (!error && response.statusCode == 200) {
                        res.send(body);
                    } else {
                        res.send(error);
                    }
                })
            })
```

The `curl` response is

```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 3000 (#0)
> POST /image.post HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 192805
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------5a0630fbf97c3283
> 
< HTTP/1.1 100 Continue
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

But I get an error that seems to be related to the post body.

```
[Mon Mar 12 2018 17:50:57 GMT+0100 (CET)] trapped error code: message:First argument must be a string or Buffer stack:TypeError: First argument must be a string or Buffer
    at write_ (_http_outgoing.js:645:11)
    at ClientRequest.write (_http_outgoing.js:620:10)
    at Request.write (/node_modules/request/request.js:1501:27)
```

I'm using `cURL` to post the image like this:

`curl -v -X POST -F "image=@data/img.jpg" "http://localhost:3000/image.post"`

The proxied server works properly when called with no proxy.

**Comment by loretoparisi** [comment]
The last attempt was to use `formData`, and add `json:true` to process the response from the proxied backend. In this way I have got a response from it (error). In this case I'm still not able to forward the request body (the image):

```javascript
app.post(self._options.baseUrl + '/image.post', function (req, res) {
                delete req.headers.host;
                var headers = req.headers;
                headers['Content-Type'] = 'application/octet-stream';
                headers['Content-Length'] =  req.body.length;
                request.post('http://localhost:9080/image.post',
                    {
                        method: 'POST',
                        headers: headers,
                        encoding: null, //  if you expect binary data
                        responseType: 'buffer',
                        json: true,
                        formData: req.body
                    },
                    function (error, response, body) {
                        console.log(response.statusCode, error, body);
                        if (!error && response.statusCode == 200) {
                            res.send(body);
                            res.end();
                        } else {
                            var error = new Error('image error');
                            res.send({ error: error.message });
                            res.end();
                        }
                    })
            })
```

**Comment by Kay2dan** [comment]
I am no authority on this, this being my first few hours with Request.js, however, I noticed that the signature required as per [the docs here](https://www.npmjs.com/package/request#forms) is something like this:

request.post('http://localhost:9080/image.post',
                    {
                        form : {
                            method: 'POST',
                            headers: headers,
                            encoding: null, //  if you expect binary data
                            responseType: 'buffer',
                           json: true,
                           body: req.body
                    },
                  ...
