### ISSUE TITLE
 Error: read ECONNRESET     at TCP.onread (net.js:602:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' 

### ISSUE THREAD

**Issue by hktalent** [request/request#2911]
```
{ Error: read ECONNRESET
    at TCP.onread (net.js:602:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }

but 
curl http://xxxxxxxxxx
is ok
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:proxy listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:version listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:url listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:t3 listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:install listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:verbose listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:struts2 listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:cmd listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:timeout listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:pool listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:test listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:menu listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:webshell listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:method listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:host listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:keys listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 --help listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit
(node:21537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by shinriyo** [comment]
It happens in TestCafe too!!!

**Comment by thecpdubguy** [comment]
I'm getting this using OSX 10.11.6 cannot reproduce consistently. Sometimes request fails at start of application, other times, request fails sometime after start of application.
`node -v` v8.11.3
`npm -v` 5.6.0
I have also seen reports about node 8.x having these issues, maybe a node problem instaed of request problem? I have not seen a fix that works for me.

**Comment by unstephenk** [comment]
Anyone have a solution for this? Im on 10.9.0 making easily over 100 requests to a remote server.

**Comment by hktalent** [comment]
@unsetbit @thecpdubguy @shinriyo 
```
	n_maxLs = 333
EventEmitter.prototype._maxListeners = n_maxLs;
var _fnNull = function(e){if(program && program.verbose)console.log(e)};
process.on('uncaughtException', _fnNull);
process.on('unhandledRejection', _fnNull);

EventEmitter.defaultMaxListeners = n_maxLs;
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;
```

**Comment by unstephenk** [comment]
@hktalent just throw this at the top of the file?
