### ISSUE TITLE
Proxy Issue

### ISSUE THREAD

**Issue by CharlieJ1911** [request/request#2986]
Hey there,
when using proxies via a request I get:
```js
{ Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND http http:80
    at ClientRequest.onError (xxxxxx\node_modules\tunnel-agent\index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }
```

**Comment by jd-carroll** [comment]
It looks like your url is wrong, can you paste your invoking code?  (Otherwise, this is really unhelpful)

**Comment by CharlieJoseph** [comment]
Yep sorry, @jd-carroll.
```java
function doVote(username, captchaKey, proxy, csrf){
    console.log(proxy);
    request.post({
        url: voteUrl,
        proxy: "http://" + proxy,
        form: {
            "username": username,
            "g-recaptcha-response": captchaKey,
            "captcha": 1
        },
        headers: {
            'User-Agent': "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
        }
    }, function(err,httpResponse,body) {
        console.log(httpResponse);
        if(err){
            console.log("===================================");
            console.log(err);
            console.log("===================================");
            return;
        }
        console.log(body);
        console.log(`Site returned Response Code ${httpResponse.statusCode}`)
        if(body.includes("The CAPTCHA needs to be solved.")){
            console.log("Couldn't send vote!");
        } else {
            console.log("Voted!");
        }
    });
}
```

**Comment by CharlieJoseph** [comment]
Reading on further, it seems a common fault with the module that executing multiple requests breaks it.

**Comment by rasmuslp** [comment]
`request` has no problems executing multiple requests. Not any I have experienced at least.

What value do you pass as the `proxy` parameter when invoking `doVote`?

**Comment by CharlieJoseph** [comment]
I have a function that gets a random proxy from my .json file. It'll return a HTTP proxy such as 142.535.252.535:80 etc

**Comment by CharlieJoseph** [comment]
```
[INFO] Using Proxy: 45.43.***.***:1971
[INFO] Couldn't send Request! Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 1971 1971:80
```

Even with a basic proxy request, I seem to get the following..?

**Comment by CharlieJoseph** [comment]
I fixed that, however it was passed in the parameter. It seems however my post request doesn't fire as it should, here is my code:
```js
function executeVote(username, token, proxy, csrf){
    rp({
        url: voteUrl,
        method: "POST",
        proxy: "http://" + proxy,
        headers: {
            'user-agent': userAgent
        },
        form: {
            'g-recaptcha-response': token,
            'captcha': 1,
            'username': username,
            'csrf': csrf
        },
        followAllRedirects: true,
        jar: cookies
    }).then(function (body) {
        console.log(body);
        if(body.includes("The CAPTCHA needs to be solved.")){
            console.log("[INFO] Captcha Issue.");
        } else {
            console.log("[INFO] Potentially Voted");
        }
    }).catch(function (err) {
        console.log("[INFO] Couldn't send vote! " + err.message);
    });
}```

Example URL: https://minecraftservers.org/vote/456859

It just doesn't do the actual vote.

Ty

**Comment by rasmuslp** [comment]
It looks valid to me.

My best suggestion at this point would be to run the request through a local proxy to inspect the traffic.

On macOS you can try https://www.charlesproxy.com 
On Windows you can try https://www.telerik.com/fiddler
