### ISSUE TITLE
get request using proxy error

### ISSUE THREAD

**Issue by FunnyCheese** [request/request#3007]
get request using proxy: http://login:pass@0.0.0.0:8000

{ Error: InvalidLoginAuthCode
    at SteamUser._handlers.(anonymous function) (/root/bot/node_modules/steam-user/components/logon.js:363:16)
    at SteamUser._handleMessage (/root/bot/node_modules/steam-user/components/messages.js:249:30)
    at CMClient.emit (events.js:182:13)
    at CMClient.EventEmitter.emit (domain.js:442:20)
    at CMClient._netMsgReceived (/root/bot/node_modules/steam-client/lib/cm_client.js:323:8)
    at CMClient.handlers.(anonymous function) (/root/bot/node_modules/steam-client/lib/cm_client.js:603:8)
    at CMClient._netMsgReceived (/root/bot/node_modules/steam-client/lib/cm_client.js:305:24)
    at TCPConnection.emit (events.js:182:13)
    at TCPConnection.EventEmitter.emit (domain.js:442:20)
    at TCPConnection._readPacket (/root/bot/node_modules/steam-client/lib/tcp_connection.js:183:7) eresult: 65 }

**Comment by Taewa** [comment]
Hi @FunnyCheese 
How did you manage it?
I am having the same issue.

**Comment by nodeplusplus** [comment]
Set `pool:false` will temporary solve your issue. I think we got stuck at create agent.

**Comment by xeinebiu** [comment]
> Set `pool:false` will temporary solve your issue. I think we got stuck at create agent.

Setting pool to false makes usage of proxy to none at all.

When I do a get requests to any IP Logger via POSTMAN and your suggestion, I get my real IP from Request.js
