### ISSUE TITLE
 source.on('error', function() {}); while using form data

### ISSUE THREAD

**Issue by Balaji1294** [request/request#3020]
Hi,

I am using form data and below is yml :+1: 
scenarios:
 - name: "UploadDoc"
   flow:
    - post:
        url: "/application/My0001"
        formData:
          file:
            fromFile: "../files/Driving_License.jpg"
          filename: "Driving_License"
          tags: "ID Verification"

When I run this using artillery run I am getting the below error:
/usr/lib/node_modules/artillery/node_modules/delayed-stream/lib/delayed_stream.js:33
  source.on('error', function() {});
         ^

TypeError: source.on is not a function
    at Function.DelayedStream.create (/usr/lib/node_modules/artillery/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/usr/lib/node_modules/artillery/node_modules/combined-stream/lib/combined_stream.js:44:37)
    at FormData.append (/usr/lib/node_modules/artillery/node_modules/form-data/lib/form_data.js:74:3)
    at appendFormValue (/usr/lib/node_modules/artillery/node_modules/request/request.js:322:21)
    at Request.init (/usr/lib/node_modules/artillery/node_modules/request/request.js:333:11)
    at new Request (/usr/lib/node_modules/artillery/node_modules/request/request.js:127:8)
    at request (/usr/lib/node_modules/artillery/node_modules/request/index.js:53:10)
    at done (/usr/lib/node_modules/artillery/core/lib/engine_http.js:437:9)
    at /usr/lib/node_modules/artillery/node_modules/async/lib/async.js:52:16
    at iterate (/usr/lib/node_modules/artillery/node_modules/async/lib/async.js:260:24)

Let me know whats wrong..

Thanks

**Comment by abrodeur** [comment]
I was having the same issues. It was caused by having turn the response into a promise 
const {promisify} = require('util');           
const request = promisify(require('request'));
