### ISSUE TITLE
Error: Invalid protocol: ftp:

### ISSUE THREAD

**Issue by pankajcogability** [request/request#3040]
```
`var request = require('request');

var url = "ftp://ftp.hp.com/pub/hpdm/Documentation/WhitePapers/4.5/WP_HPDM_FTP_Configuration.pdf";

startTask().then(function (fullfill) {
console.log(fullfill)
}).catch(function (err) {
console.log(err)
});

function startTask() {
return new Promise(function (fulfill, reject) {
var options =
{
uri: url,
method: "GET",
encoding: null,
resolveWithFullResponse: true,
};
request(options)
.then(function (err, results, body) {
if (err) {
console.log(err);
} else {
console.log(results.statusCode);
console.log(results.body.toString());
}
}.bind(this))
.catch(function (err) {
console.log(err);
return fulfill(true);
});
}.bind(this));
}`

```
**When i run this code getting an error any body can help me to resolve it.

Error is**

```
`/usr/local/bin/node /home/gsolc/Documents/pankaj/cogAbility/demos/ecma6/request.js
Error: Invalid protocol: ftp:
at Request.init (/home/gsolc/Documents/pankaj/cogAbility/demos/ecma6/node_modules/request/request.js:458:31)
at new Request (/home/gsolc/Documents/pankaj/cogAbility/demos/ecma6/node_modules/request/request.js:127:8)
at request (/home/gsolc/Documents/pankaj/cogAbility/demos/ecma6/node_modules/request/index.js:53:10)
at /home/gsolc/Documents/pankaj/cogAbility/demos/ecma6/request.js:28:9
at new Promise ()
at startTask (/home/gsolc/Documents/pankaj/cogAbility/demos/ecma6/request.js:20:12)
at Object. (/home/gsolc/Documents/pankaj/cogAbility/demos/ecma6/request.js:13:1)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)

Process finished with exit code 0
`
```

**Comment by ultimate-tester** [comment]
FTP is a completely different protocol than HTTP and HTTPS. Request doesn't support FTP.

**Comment by mayank13** [comment]
Curl supports FTP with and without proxy. For example: curl -p -x $http_proxy ftp://ftp.gnu.org/README works fine. SImilar support should be added for request module.
