### ISSUE TITLE
 Error: ESOCKETTIMEDOUT     at ClientRequest.<anonymous>

### ISSUE THREAD

**Issue by hktalent** [request/request#3042]
node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.emitTimeout (_http_client.js:714:34)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:447:8)
    at ontimeout (timers.js:457:11)
    at tryOnTimeout (timers.js:327:5)
    at listOnTimeout (timers.js:301:5) code: 'ESOCKETTIMEDOUT', connect: false }

**Comment by linvi** [comment]
@reconbot we are experiencing the same issue, could you provide information on the topic and some workarounds.

Cheers,
Linvi

**Comment by linvi** [comment]
@reconbot we are trying to create a sample code block to reproduce the issue but so far we have not managed to. For now we are only experiencing it randomly. Will update you when we have more information.

* NodeJS Version: 8.12.0
* Request version: 2.81.0
* OS Version: Docker Ubuntu 16.04

**Comment by hktalent** [comment]
@linvi @reconbot @jchris @voodootikigod 
<img width="852" alt="image" src="https://user-images.githubusercontent.com/18223385/49264956-4a5c6200-f48b-11e8-89fa-d9bba3bb1736.png">
agent: false, pool: {maxSockets: 200},
_req = req.defaults(_t.reqOption = option);

		return _req;

**Comment by Lohith4** [comment]
@hktalent @linvi  hey there, facing the same issue. Could you please help me how to solve this? Thanks
