### ISSUE TITLE
howto avoid - (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

### ISSUE THREAD

**Issue by framlin** [request/request#311]
I get a TRACE that tells me, that I should increase the listener-limit.
How can I call emitter.setMaxListeners() for request or how can I avoid the problem?

**Comment by Seojiwoong** [comment]
https://github.com/request/request/issues/311

**Comment by krazylearner** [comment]
same here 

(node) warning: possible EventEmitter memory leak detected. 11 drain listeners a
dded. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:179:15)
    at WriteStream.Readable.on (_stream_readable.js:671:33)
    at Request.Stream.pipe (stream.js:65:8)
    at Request.pipe (C:\Users\abhilash\Desktop\CHARLES\gerrit_checkout\March_17_
2015\nodejs.folders.io\node_modules\request\request.js:1329:34)
    at Fio.post (C:\Users\abhilash\Desktop\CHARLES\gerrit_checkout\March_17_2015
\nodejs.folders.io\api.js:9:12661)
    at onList (C:\Users\abhilash\Desktop\CHARLES\gerrit_checkout\March_17_2015\n
odejs.folders.io\folders\folders-stub.js:9:759)
    at onList (C:\Users\abhilash\Desktop\CHARLES\gerrit_checkout\March_17_2015\n
odejs.folders.io\test\listen.js:51:10)
    at Object.<anonymous> (C:\Users\abhilash\Desktop\CHARLES\gerrit_checkout\Mar
ch_17_2015\nodejs.folders.io\test\listen.js:41:5)
    at Object.Conduit._targetStep.fn (C:\Users\abhilash\Desktop\CHARLES\gerrit_c
heckout\March_17_2015\nodejs.folders.io\node_modules\postal\node_modules\conduit
js\lib\conduit.js:40:43)
    at Object.next (C:\Users\abhilash\Desktop\CHARLES\gerrit_checkout\March_17_2
015\nodejs.folders.io\node_modules\postal\node_modules\conduitjs\lib\conduit.js:
70:33)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners a
dded. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:179:15)
    at WriteStream.Readable.on (_stream_readable.js:671:33)
    at Request.Stream.pipe (stream.js:99:8)
    at Request.pipe (C:\Users\abhilash\Desktop\CHARLES\gerrit_checkout\March_17_
2015\nodejs.folders.io\node_modules\request\request.js:1329:34)
    at Fio.post (C:\Users\abhilash\Desktop\CHARLES\gerrit_checkout\March_17_2015
\nodejs.folders.io\api.js:9:12661)
    at onList (C:\Users\abhilash\Desktop\CHARLES\gerrit_checkout\March_17_2015\n
odejs.folders.io\folders\folders-stub.js:9:759)
    at onList (C:\Users\abhilash\Desktop\CHARLES\gerrit_checkout\March_17_2015\n
odejs.folders.io\test\listen.js:51:10)
    at Object.<anonymous> (C:\Users\abhilash\Desktop\CHARLES\gerrit_checkout\Mar
ch_17_2015\nodejs.folders.io\test\listen.js:41:5)
    at Object.Conduit._targetStep.fn (C:\Users\abhilash\Desktop\CHARLES\gerrit_c

**Comment by dutchakdev** [comment]
+1 
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
  at Request.EventEmitter.addListener (events.js:160:15)
  at Request.init (/home/ubuntu/workspace/megatalog-crawler/node_modules/request/request.js:667:8)
  at Redirect.onResponse (/home/ubuntu/workspace/megatalog-crawler/node_modules/request/lib/redirect.js:149:11)
  at Request.onRequestResponse (/home/ubuntu/workspace/megatalog-crawler/node_modules/request/request.js:1108:22)
  at ClientRequest.EventEmitter.emit (events.js:95:17)
  at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
  at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
  at Socket.socketOnData [as ondata] (http.js:1583:20)
  at TCP.onread (net.js:527:27)

**Comment by afshinm** [comment]
Same issue:

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:160:15)
    at Request.init (/var/www/floatalk.it/src/node_modules/request/request.js:667:8)
    at Redirect.onResponse (/var/www/floatalk.it/src/node_modules/request/lib/redirect.js:149:11)
    at Request.onRequestResponse (/var/www/floatalk.it/src/node_modules/request/request.js:1108:22)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1692:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socketOnData [as ondata] (http.js:1587:20)
    at TCP.onread (net.js:527:27)

**Comment by jamlen** [comment]
:+1:  and I'm using v0.12.2

**Comment by elliotbonneville** [comment]
Having the same issue.

**Comment by shotlom** [comment]
I'm getting this issue also when using request with ```.pipe()```

happy to increase the number of listeners, but can I do that if I'm using pipes?

**Comment by shotlom** [comment]
@mikeal 2 yrs ago you mentioned, "we don't cleanup the pipe listener", do you have an example of how I can cleanup the pipe listener manually? 

I'm piping the return to a number of data cleansers and tasks but as soon as I hit 11 request.get() calls my script falls over.
```
[someArray of urls]

for ( i < someArray.length){
  request.get(someUri)
  .pipe(someCleansingFunction)
 .pipe(someSavingFunction)
 .how( do I cleanup the pipe listener now that I've finished cleansing & saving?)
}

```

**Comment by jefersonbentes** [comment]
+1

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
at PoolConnection.EventEmitter.addListener (events.js:160:15)
at /home/jeferson/workspacejs/syncserver/src/prod/dbconnection.js:32:20
at Ping.onOperationComplete [as _callback] (/home/jeferson/workspacejs/syncserver/node_modules/mysql/lib/Pool.js:99:5)
at Ping.Sequence.end (/home/jeferson/workspacejs/syncserver/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
at Ping.Sequence.OkPacket (/home/jeferson/workspacejs/syncserver/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
at Protocol._parsePacket (/home/jeferson/workspacejs/syncserver/node_modules/mysql/lib/protocol/Protocol.js:274:23)
at Parser.write (/home/jeferson/workspacejs/syncserver/node_modules/mysql/lib/protocol/Parser.js:77:12)
at Protocol.write (/home/jeferson/workspacejs/syncserver/node_modules/mysql/lib/protocol/Protocol.js:39:16)
at Socket.<anonymous> (/home/jeferson/workspacejs/syncserver/node_modules/mysql/lib/Connection.js:96:28)
at Socket.EventEmitter.emit (events.js:95:17)

**Comment by RathaR** [comment]
+1, I have the same problem with pipe...

**Comment by travischoma** [comment]
+1, happens often with nytimes.com links for me. Is there a work around for this bug?

Aug 31 11:14:41 x app/web.1:  (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit. 
Aug 31 11:14:41 x app/web.1:  Trace 
Aug 31 11:14:41 x app/web.1:      at Request.addListener (events.js:160:15) 
Aug 31 11:14:41 x app/web.1:      at Request.start (/app/node_modules/request/request.js:947:8) 
Aug 31 11:14:41 x app/web.1:      at Request.end (/app/node_modules/request/request.js:1732:10) 
Aug 31 11:14:41 x app/web.1:      at end (/app/node_modules/request/request.js:704:14) 
Aug 31 11:14:41 x app/web.1:      at Object._onImmediate (/app/node_modules/request/request.js:718:7) 
Aug 31 11:14:41 x app/web.1:      at processImmediate [as _immediateCallback] (timers.js:354:15) 
Aug 31 11:14:41 x app/web.1:  [Error: Exceeded maxRedirects. Probably stuck in a redirect loop http://www.nytimes.com/2015/06/28/magazine/confessions-of-a-seduction-addict.html?_r=4]

**Comment by ahildoer** [comment]
Hi @mikeal,

This still happens with just basic GET requests, no pipes, no magic fairy dust, etc.

Regardless of what server we talk to, and what issues that server has, it should not cause a problem in our client code. If we connect to a server and it streams back random binary, and nothing of HTTP protocol at all, I would expect that the err response be populated. We should not be kicking off error messages and warnings. Also, ignoring the leak with maxListeners(0) is not a solution. Its pretending the problem doesn't exist as our servers slowly crash.

**Comment by aggied** [comment]
+1 @travischoma same here.

**Comment by lawrips** [comment]
Not sure if it's the same issue that everyone else is facing here but this state is reproable (at least on Node 0.12.6) by:

1. Setting http.globalAgent.maxSockets = 1 (or a similarly low #)
2. Making lots of requests to the same server

What i see is 1 socket connection (or however many you set in #1) and then as requests get queued, this exception will eventually get triggered. 

My case is somewhat artificial as I'm setting maxSockets to be low. But i believe that pre node 0.12, the default size was 5 and in theory, this error could occur whenever there are significantly more requests than available sockets?

**Comment by Psopho** [comment]
I've overcome this by setting maxRedirects:5 which raises an error correctly and doesn't crash and burn

**Comment by anmolgupta** [comment]
I have this same issue when I am trying to implement SSE with nodejs. 

(node) warning: possible EventEmitter memory leak detected. 11 notify listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:179:15)

**Comment by nanvel** [comment]
`removeAllListeners('data')` looks like fixed the issue for me.
Be careful, I am not sure it has no side effects.

```
function getPage(pageURL) {
  return new Promise(function(resolve, reject) {
    let chunks = []
    let reqPipe = request({
      uri: pageURL,
      method: 'GET'
    }).pipe(iconv)

    reqPipe.on('data', function(chunk) {
      chunks.push(chunk)
    }).once('end', function() {
      var str = Buffer.concat(chunks).toString()
      reqPipe.removeAllListeners('data')
      resolve(str)
    })
  })
}
```

**Comment by justechn** [comment]
I am doing an npm install with a local repository and getting this error. What is the solution?

`npm install -g git+http://stash/scm/ss/generator-lambda.git`

**Comment by fishcharlie** [comment]
I'm having this same problem with `nytimes.com`. Was anyone able to fix this?

**Comment by smelted-code** [comment]
@fishcharlie Same issue here with NYT. Lowering the number of redirects (like @Psopho  and @chmac suggest) seems like a viable workaround.

**Comment by shiftie** [comment]
Adding `{maxRedirects: 5}` option to the function call prevents the memory leak issue & instead populates the `err` argument in the callback function.

**Comment by ttback** [comment]
Didn't know this was still relevant issue in 2017. I made a library to try to have it working with request 4 years ago. You can try to see if it helps.

**Comment by Zearin** [comment]
> Didn't know this was still relevant issue in 2017

It’s 2018 😋
