### ISSUE TITLE
retry on ECONNREST broken

### ISSUE THREAD

**Issue by themez** [request/request#3131]
### Summary

I found ECONNRESET is handled by retry in this PR #148 , but since forever agent is only used in Nodejs v0.xx, it's not working currently.

### Simplest Example to Reproduce

```js
const Agent = require("http").Agent;

const agent = new Agent({ keepAlive: true });
const request = require('request') 
http
  .createServer((req, res) => {
    res.write("foo\n");
    res.end();
  })
  .listen(3000);

setInterval(() => {
  request.get('http://localhost:3000', { agent }, (err, res) => {      
      if (err) console.error(err)
  });
}, 5000);
```

### Expected Behavior

No error.

### Current Behavior

Encounter an error if wait 10~20 seconds.
```
{ Error: socket hang up
    at createHangUpError (_http_client.js:342:15)
    at Socket.socketCloseListener (_http_client.js:377:23)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12) code: 'ECONNRESET' }
```

### Possible Solution

Maybe make req as resued in [http_agent](https://github.com/nodejs/node/blob/master/lib/_http_agent.js#L320), or create a wrapper for default agent.

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.88.0
| node             | 10.12.0
| npm              | 6.4.1
| Operating System | MacOS Mojave 10.14.1

**Comment by themez** [comment]
Since nodejs/node/pull/29715 is landed, this issued could be fixed.
