### ISSUE TITLE
JSON Body with 'on' causes TypeError

### ISSUE THREAD

**Issue by zk0d** [request/request#3163]
### Summary
Making a request with a JSON body that includes an 'on' parameter throws "TypeError: self.on is not a function"
 

### Simplest Example to Reproduce
var request = require('request');

request.post('http://192.168.0.1', body={'on': 1})

### Expected Behavior
Sending JSON body irregardless of content, simply changing the word 'on' fixes this problem, but certain API's I am trying to use require an 'on' parameter in the requests body.

### Current Behavior
When running the example above the following is thrown, no matter what I change so long as the 'on' parameter exists I get the same result:

/home/user/Desktop/test/node_modules/request/request.js:187
    self.on('error', self.callback.bind())
         ^

TypeError: self.on is not a function
    at Request.init (/home/user/Desktop/test/node_modules/request/request.js:187:10)
    at new Request (/home/user/Desktop/test/node_modules/request/request.js:127:8)
    at request (/home/user/Desktop/test/node_modules/request/index.js:53:10)
    at Function.put (/home/user/Desktop/test/node_modules/request/index.js:61:12)
    at Object.<anonymous> (/home/user/Desktop/test/index.js:4:9)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:822:10)

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.88.0
| node             | v12.2.0
| npm              | 6.9.0
| Operating System | Ubuntu 18.04.2 LTS

This is my first time posting an issue on Github, apologies if I left anything out, more than happy to edit my post as needed.

**Comment by and-kost** [comment]
Last time I made POST requests too and I used the next way. It executes correctly.
Maybe it will helpful for you.

```
var https = require('https');
var querystring = require('querystring');

let post_data = querystring.stringify({
  on: 1
});
var options = {
  hostname: 'localhost',
  port: 9090,
  method: 'POST',
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded',
    'Content-Length': Buffer.byteLength(post_data)
  }
};

req.write(post_data);
req.end();
```
