### ISSUE TITLE
Error: getAllCookies is not implemented (therefore jar cannot be serialized)

### ISSUE THREAD

**Issue by lucasvieceli** [request/request#3178]
Hi, I'm using the "instgram-web-api" library, which uses your library

is returning me the following error in some requests

```
rror: getAllCookies is not implemented (therefore jar cannot be serialized)
    at FileCookieStore.Store.getAllCookies (/var/www/lucas/instagram/node_modules/tough-cookie/lib/store.js:74:9)
    at CookieJar.serialize (/var/www/lucas/instagram/node_modules/request/node_modules/tough-cookie/lib/cookie.js:1273:14)
    at CookieJar.serializeSync (/var/www/lucas/instagram/node_modules/request/node_modules/tough-cookie/lib/cookie.js:1402:18)
    at CookieJar.toJSON (/var/www/lucas/instagram/node_modules/request/node_modules/tough-cookie/lib/cookie.js:1294:15)
    at JSON.stringify (<anonymous>)
    at Object.exports.log (/var/www/lucas/src/index.ts:113:21)
    at Object.<anonymous> (/var/www/lucas/src/instagram.ts:191:13)
    at Generator.throw (<anonymous>)
    at rejected (/var/www/lucas/instagram/instagram.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
 code
```
import * as FileCookieStore from 'tough-cookie-filestore2';
const Instagram      = require('instagram-web-api');

        const proxy = await getProxyUrl(id);
        const cookieStore = new FileCookieStore(`./contas/${usuario}.json`);
        const client = new Instagram({
            username: usuario,
            password: senha,
            cookieStore
        }, {
            language: 'pt-BR',
            proxy
        });
```

I'm posting here because I did not find the solution

GOOGLE TRANSLATE :D

**Comment by jdgabriel** [comment]
Any solution to the problem? I'm still here xD
---
Alguma solução para o problema? Estou na mesma aqui xD

**Comment by lucasvieceli** [comment]
> ## Any solution to the problem? I'm still here xD
> Alguma solução para o problema? Estou na mesma aqui xD

Opa, você ta querendo usar essa lib para que ? em especifico

**Comment by jdgabriel** [comment]
Construindo um projeto pessoal, verificação de seguidores, comentários e curtidas...
Você conseguiu resolver este problema?

**Comment by lucasvieceli** [comment]
eu desenvolvi meu proprio, mas parei pq instagram agora bloqueia forte, mas posso te dar umas instruções  me manda msg 47984783223

**Comment by jdgabriel** [comment]
link?

**Comment by lucasvieceli** [comment]
whatsapp
https://api.whatsapp.com/send?phone=5547984783223

**Comment by jdgabriel** [comment]
chamei... xD
