### ISSUE TITLE
Parse Error: Invalid header value char

### ISSUE THREAD

**Issue by bobo23** [request/request#3187]
### Summary
We send a request to http://www.kooora.com/?n=798574&o=ncsa and always get the error Parse Error: Invalid header value char back.

### Simplest Example to Reproduce

```js
request({
  method: 'GET',
        url: http://www.kooora.com/?n=798574&o=ncsa,
        jar: true,
        headers: {
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.170'
        },
        encoding: null,
        timeout: 3500
})
```

### Your Environment

| software         | version
| --------------| -------
| request           | 2.88.0
| node               | 12.7.0
| npm                | 6.10.0
| Operating System | MacOS 10.14.4

**Comment by GeekyDeaks** [comment]
I think you found a problem with node.js

The above works for me under 8.11.0, but I get the same error with 12.7.0, so I tried using the core modules and found the error still occurs e.g.:

```
const https = require('https')
const options = {
  hostname: 'www.kooora.com',
  port: 443,
  path: '/?n=798574&o=ncsa',
  method: 'GET'
}

const req = https.request(options, res => {
  console.log(`statusCode: ${res.statusCode}`)

  res.on('data', d => {
    process.stdout.write(d)
  })
})

req.on('error', error => {
  console.error(error)
})

req.end()
```

gives:

```
Error: Parse Error: Invalid header value char
    at TLSSocket.socketOnData (_http_client.js:449:22)
    at TLSSocket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at TLSSocket.Readable.push (_stream_readable.js:210:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:166:17) {
  bytesParsed: 945,
  code: 'HPE_INVALID_HEADER_TOKEN',
  reason: 'Invalid header value char',
  rawPacket: <Buffer 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d 0a 43 61 63 68 65 2d 43 6f 6e 74 72 6f 6c 3a 20 70 72 69 76 61 74 65 0d 0a 43 6f 6e 74 65 6e 74 2d 54 ... 1402 more bytes>
}
```

**Comment by GeekyDeaks** [comment]
ok, quick bit of digging and it seems it might actually be the website doing funky stuff and not adhering to spec:

https://github.com/nodejs/node/issues/27711
