### ISSUE TITLE
stream.push() after EOF (googleapis npm module)

### ISSUE THREAD

**Issue by bcoe** [request/request#3192]
### Summary

A user reported an issue with [googleapis](https://www.npmjs.com/package/googleapis), in which they're experiencing an intermittent issue streaming files to Google Drive.

In the process of debugging the issue we found that:

* the error goes away if the user completely downloads the file, and uploads the bytes to Drive.
* the user switches to using `got` or `node-fetch` in streaming mode.

This makes me think the issue might potentially be related to requests' stream implementation.

### Simplest Example to Reproduce

@jayjanssen provided the following code:

```js
var auth, clientId, clientSecret, credentials, drive, file_url, filename, folder, google, mime, redirectUri, request, util;

  util = require('util');
  request = require("request");
  ({google} = require('googleapis'));

  auth = new google.auth.OAuth2(clientId, clientSecret, redirectUri);
  auth.credentials = credentials;

  drive = google.drive({
    version: 'v3',
    auth
  });

  filename = 'fatboy.png';
  mime = 'image/png';
  file_url = "http://findicons.com/files/icons/1267/futurama_vol_4_the_robots/256/fat_bot.png";

  (async function() {
    var resp;
    resp = (await drive.files.create({
      resource: {
        name: filename,
        mimeType: mime,
        parents: [folder]
      },
      media: {
        body: request.get(file_url)
      }
    }));
    return console.log(util.inspect(resp));
  })();
```

@jayjanssen can you elaborate on how often this issue cropped up, how many uploads on average were you performing before noticing a failure?

### Expected Behavior

Streaming directly to Google Drive succeeds without failure.

### Current Behavior

Periodically the following error is observed:

```bash
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_PUSH_AFTER_EOF] [ERR_STREAM_PUSH_AFTER_EOF]: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:263:32)
    at PassThrough.Readable.push (_stream_readable.js:210:10)
    at PassThrough.Transform.push (_stream_transform.js:150:32)
    at PassThrough.afterTransform (_stream_transform.js:94:10)
    at PassThrough._transform (_stream_passthrough.js:44:3)
    at PassThrough.Transform._read (_stream_transform.js:189:10)
    at PassThrough.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:417:12)
    at writeOrBuffer (_stream_writable.js:401:5)
    at PassThrough.Writable.write (_stream_writable.js:301:11)
    at ProgressStream.ondata (_stream_readable.js:713:22)
    at ProgressStream.emit (events.js:203:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at ProgressStream.Readable.push (_stream_readable.js:210:10)
    at ProgressStream.Transform.push (_stream_transform.js:150:32)
    at ProgressStream._transform (/Users/jayjanssen/Src/google_drive_bug/node_modules/googleapis-common/build/src/apirequest.js:259:14)
    at ProgressStream.Transform._read (_stream_transform.js:189:10)
    at ProgressStream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:417:12)
    at writeOrBuffer (_stream_writable.js:401:5)
    at ProgressStream.Writable.write (_stream_writable.js:301:11)
    at Request.ondata (internal/streams/legacy.js:17:31)
    at Request.emit (events.js:203:13)
    at IncomingMessage.<anonymous> (/Users/jayjanssen/Src/google_drive_bug/node_modules/request/request.js:1080:12)
    at IncomingMessage.emit (events.js:203:13)
    at IncomingMessage.Readable.read (_stream_readable.js:508:10)
    at flow (_stream_readable.js:977:34)
    at resume_ (_stream_readable.js:958:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at PassThrough.onerror (_stream_readable.js:737:7)
    at PassThrough.emit (events.js:203:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at readableAddChunk (_stream_readable.js:263:9)
    at PassThrough.Readable.push (_stream_readable.js:210:10)
    [... lines matching original stack trace ...]
```

### Possible Solution

Could this relate to request using an older version of the streams API, I'm wondering if we could have also solved the problem by sending the request through a [PassThrough stream](https://nodejs.org/api/stream.html#stream_class_stream_passthrough).

**Comment by mikeal** [comment]
Looking at the exception it would appear that we *are* using core’s PassThrough stream, so I’m not sure what you mean by “old version.”

This error is consistent with cases where someone writes to a stream after it has closed, which is a valid error and needs to be handled by user error handling. In your use of request’s streaming API, are you listening for stream “end” **and** “error” events and cleaning up appropriately?

request does a lot of work to propogate all errors to the request instance’s stream interface but, with the Stream API, you still need to handle them properly and *never* attempt to write after the stream has closed. This is obviously much easier with async iterators instead of the stream api, which is why we’re deprecating request ;)

**Comment by jayjanssen** [comment]
I was using an older version of `googleapis` (22.2.0) with `request` 2.88.0 and it was working fine.  I only got the issue when I upgraded to `googleapis` 42.0.0.  

Also strangely, the issue is intermittent with http requests, but https trigger it 100% of the time in my test.  I also determined got and node-fetch didn't seem to have the issue:

 ```coffee
   file_url = "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png"

  # Breaks
  stream = request.get file_url
  # Works
  stream = got file_url, {stream: true}
 
  resp = await drive.files.create {
    resource: {
      name: filename
      mimeType: mime
      parents: [folder]
    }
    media: {
      body: stream
    }
  }
```


I'm not convinced it is a request issue necessarily, but it's interesting that the newer libraries don't seem have the same issue.  

My workaround is to not use `request`, but I want to at least document the issue.  Thanks the great lib BTW!  It's been my faithful companion many years.
