### ISSUE TITLE
Error: write EPROTO

### ISSUE THREAD

**Issue by loretoparisi** [request/request#3233]
I'm using

```
ip-192-168-1-52:api loretoparisi$ node --version
v12.13.1
ip-192-168-1-52:api loretoparisi$ npm --version
6.12.1
```

Error: write EPROTO 4450674112:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16) {
  errno: 'EPROTO',
  code: 'EPROTO',
  syscall: 'write'
}
 [Wed Nov 20 2019 17:40:30 GMT+0100 (Central European Standard Time)] RequestGetP error:{
  "errno": "EPROTO",
  "code": "EPROTO",
  "syscall": "write"
}
Error: write EPROTO 4450674112:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)
Error: write EPROTO 4450674112:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)

**Comment by 9w** [comment]
I had the same problem and solved it by using agent option
```
agent: new Agent({ rejectUnauthorized: false })
```

Agent is from https module.
```
import { Agent } from 'https';
```

I hope it works for you, too.

**Comment by loretoparisi** [comment]
thank you @9w!

**Comment by ouss4m4** [comment]
just had a similar problem, 
my dev machine had a v10.15.3 NODE installed
and in the remote i installed the latest version v12.x atm
going back to v10.15.3 quick fixed it for me

**Comment by ucfmohamed** [comment]
@9w Hello.. Can you tell me where exactly should this modification be applied ?

**Comment by 9w** [comment]
@ucfmohamed  Just add it to the options in your request like this.
```
const options = {
  url: 'https://api.github.com/repos/request/request',
  method: 'POST',
  ...,
  agent: new Agent({ rejectUnauthorized: false })
};

function callback(error, response, body) {
  ...
}

request(options, callback);
```

**Comment by Nicolaschinc** [comment]
I have the same problem like this.
but I don't know the reason why it works?
