### ISSUE TITLE
Unable to install the npm,

### ISSUE THREAD

**Issue by smileysuresh** [request/request#3392]
Can anyone help on the following error?

`npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:100:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:185:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:850:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:323:11)
npm WARN addRemoteGit     at emitOne (events.js:90:13)
npm WARN addRemoteGit     at Socket.emit (events.js:182:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:475:12)
npm WARN addRemoteGit  git://github.com/zone117x/node-stratum-pool.git resetting remote /home/ubuntu/.npm/_git-remotes/git-github-com-zone117x-node-stratum-pool-git-6a5ae48b because of error: { [Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }
npm WARN deprecated request@2.69.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git://github.com/zone117x/node-stratum-pool.git /home/ubuntu/.npm/_git-remotes/git-github-com-zone117x-node-stratum-pool-git-6a5ae48b: Cloning into bare repository '/home/ubuntu/.npm/_git-remotes/git-github-com-zone117x-node-stratum-pool-git-6a5ae48b'...
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git://github.com/zone117x/node-stratum-pool.git /home/ubuntu/.npm/_git-remotes/git-github-com-zone117x-node-stratum-pool-git-6a5ae48b: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git://github.com/zone117x/node-stratum-pool.git /home/ubuntu/.npm/_git-remotes/git-github-com-zone117x-node-stratum-pool-git-6a5ae48b: github.com[0: 13.234.176.102]: errno=Connection timed out
npm ERR! Linux 5.4.0-1058-aws
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v5.10.1/bin/node" "/home/ubuntu/.nvm/versions/node/v5.10.1/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git://github.com/zone117x/node-stratum-pool.git /home/ubuntu/.npm/_git-remotes/git-github-com-zone117x-node-stratum-pool-git-6a5ae48b
npm ERR! Cloning into bare repository '/home/ubuntu/.npm/_git-remotes/git-github-com-zone117x-node-stratum-pool-git-6a5ae48b'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 13.234.176.102]: errno=Connection timed out
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/nomp/npm-debug.log`

**Comment by Scoooolzs** [comment]
Hello! @smileysuresh, Request module is now deprecated. check the issues of deprecated [here.](https://github.com/request/request/issues/3142)
