### ISSUE TITLE
[Error: CERT_UNTRUSTED]

### ISSUE THREAD

**Issue by ralyodio** [request/request#811]
I get `[Error: CERT_UNTRUSTED]` error when hitting this url with request:

https://www.atomic-trade.com/SimpleAPI?a=markets

It works fine in browser and with curl.

**Comment by saurabh1gupta** [comment]
Hi there,

I'm facing the similar issue but only in "POST" method while "GET" is working fine. Here are the detailed information:

**Test Code:**

`
var frisby = require('frisby');
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

var CONF = process.env['CONF'];
var config = require('../config/' + CONF);
var data = require('../tests_data/batch_data.json');

frisby.globalSetup({
  request: {
    strictSSL: false,
    rejectUnauthorized: false,
    headers: {'Authorization': 'token'},
    inspectOnFailure: true 
  }
});

frisby.create('Test#1: Sunny Day scenario')
  .post(config.api_url + data.api_endpoint, data.test_strace, {rejectUnauthorized: false},  {json: true})
  .inspectHeaders()
  .inspectRequest()
  .inspectJSON()
  .expectJSON(data.batch_test_response_1)
.toss();
`

**Execution Error:**
Error-1
`   Message:
     Error: Error parsing JSON string: Unexpected token D
	Given: Destination URL may be down or URL is invalid, Error: ESOCKETTIMEDOUT
   Stacktrace:
     Error: Error parsing JSON string: Unexpected token D
	Given: Destination URL may be down or URL is invalid, Error: ESOCKETTIMEDOUT
    at _jsonParse (/usr/src/app/frisby_api/node_modules/frisby/lib/frisby.js:1219:11)
    at null.<anonymous> (/usr/src/app/frisby_api/node_modules/frisby/lib/frisby.js:650:20)
    at null.<anonymous> (/usr/src/app/frisby_api/node_modules/frisby/lib/frisby.js:1074:43)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)`

Error-2

`   Message:
     TypeError: Cannot read property 'headers' of undefined
   Stacktrace:
     TypeError: Cannot read property 'headers' of undefined
    at Frisby.<anonymous> (/usr/src/app/frisby_api/node_modules/frisby/lib/frisby.js:894:20)
    at Frisby.<anonymous> (/usr/src/app/frisby_api/node_modules/frisby/lib/frisby.js:940:8)
    at null.<anonymous> (/usr/src/app/frisby_api/node_modules/frisby/lib/frisby.js:1112:18)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)`

What should be updated here to fix these issues?

Thanks
